"""Result export: Rollwise/Meritwise Excel workbooks and PDF reports.

Purpose:
    Render calculated results into the files an examination office needs.

Modules (Phase 9, see ``development/PHASE_09_HANDOFF.md``):
    * ``excel.py`` - openpyxl workbook generation from a user-supplied
      template: Rollwise (populated in a *copy* of the template), Meritwise,
      Summary, Answer Key and Processing Log, plus header/logo/font/page-setup
      layout.
    * ``pdf.py`` - a dependency-injected PDF exporter abstraction over
      LibreOffice's headless conversion.

    Plain CSV interchange export already existed before this phase, as
    :mod:`omr_scanner.services.scan_export`, and is unaffected by it.

What does NOT belong here:
    * Calculating results. Reporting formats data that the scoring engine has
      already produced; it must never re-derive a mark.
    * Deciding who is present, absent or eligible to be reported on. Reading
      Phase 7's reconciliation and Phase 8's scoring is
      :mod:`omr_scanner.services.report_store`'s job; this package receives
      only the plain data those decisions produced.
    * Qt code. A report is generated by a service and may be produced
      headlessly.

Contract:
    * Every failure here raises :class:`omr_scanner.errors.ReportingError`
      (or a subclass of it) - see :class:`~omr_scanner.reporting.excel.ExcelReportError`
      and :class:`~omr_scanner.reporting.pdf.PdfExportError`.
    * The original template file is never opened for writing - generation
      copies its bytes first, proven by SHA-256 in the test suite.
    * Exports are written into ``<project>/exports`` and never overwrite an
      existing file silently.
"""
