"""Result export. RESERVED - no implementation in Phase 0.

Purpose:
    Render calculated results into the files an examination office needs:
    roll-wise and merit-wise Excel workbooks, CSV interchange files and PDF
    reports.

Planned modules (Phase 9, see ``development/ROADMAP.md``):
    * ``excel.py``  - openpyxl workbook generation from a user-editable template.
    * ``csv_io.py`` - plain interchange export.
    * ``pdf.py``    - printable reports.

What does NOT belong here:
    * Calculating results. Reporting formats data that the scoring engine has
      already produced; it must never re-derive a mark.
    * Qt code. A report is generated by a service and may be produced headlessly.

Contract for later phases:
    * Exports are written into ``<project>/exports`` and never overwrite an
      existing file silently.
    * Failures raise :class:`omr_scanner.errors.ReportingError`.
"""
