"""Build a result workbook from a copy of the operator's own template.

Purpose:
    The openpyxl mechanics behind Phase 9: populate the Rollwise sheet inside
    a *copy* of the supplied template, add the Meritwise/Summary/Answer
    Key/Processing Log sheets, write dynamic ``RANK.EQ`` formulas, and apply
    whatever layout an operator configured - all without ever opening the
    original template file for writing.

Scope:
    Pure(ish) spreadsheet mechanics. Takes plain data in (a
    :class:`~omr_scanner.services.report_template.TemplateRoster`, marks,
    layout settings) and writes to an output path. No database, no Qt, no
    deciding who is present or absent - that is
    :mod:`omr_scanner.services.report_store`'s job, reading Phase 7/8's
    canonical state. This module never re-derives a mark.

Preserving the template (§17, §18):
    ``copy_into`` copies the template's *bytes* before this module opens
    anything - the original file is never opened in write mode by any
    function here, so it cannot be modified regardless of what the rest of
    this module does. Cells this module does not touch keep every formatting
    attribute openpyxl loaded them with, because they are simply never
    reassigned.
"""

from __future__ import annotations

import json
import logging
import shutil
from collections.abc import Mapping
from dataclasses import dataclass, field
from datetime import datetime
from fractions import Fraction
from typing import TYPE_CHECKING, Any

from omr_scanner.domain.reporting import (
    ABSENT_MARK_DISPLAY,
    ABSENT_RANK_DISPLAY,
    column_letter,
    rank_formula,
    safe_cell_text,
)
from omr_scanner.domain.scoring import format_mark
from omr_scanner.errors import ReportingError

if TYPE_CHECKING:
    from collections.abc import Sequence
    from pathlib import Path

    from omr_scanner.domain.scoring import AnswerKey
    from omr_scanner.services.report_template import TemplateRoster

_LOGGER = logging.getLogger(__name__)


def _bold_font(**overrides: Any) -> Any:
    """A fresh bold ``openpyxl.styles.Font``, with any extra attributes set.

    ``Font.copy(...)`` looks tempting but is deprecated in current openpyxl
    (a warning this project's pytest configuration turns into a failure) and
    was never necessary here: every call site wants a *new* font on a cell
    that has not been styled yet, not a modification of one a template
    already set - this module never touches an existing template cell's
    font, only cells it creates itself on new sheets.
    """
    from openpyxl.styles import Font

    return Font(bold=True, **overrides)

MERITWISE_SHEET_NAME = "meritwise"
"""Exactly as specified, in lower case.

Excel compares sheet names case-insensitively, so this cannot collide with a
``Meritwise`` the template already has - :func:`build_meritwise_from_rollwise`
deletes any existing sheet of that name before copying, which covers both
spellings. Earlier builds wrote ``"Meritwise"``; a workbook regenerated by
this build carries the new spelling, and nothing reads the old one back."""
SUMMARY_SHEET_NAME = "Summary"
ANSWER_KEY_SHEET_NAME = "Answer Key"
PROCESSING_LOG_SHEET_NAME = "Processing Log"

_MARK_NUMBER_FORMAT = "0.00"
"""Two decimal places, matching :data:`omr_scanner.domain.scoring.MARK_DISPLAY_PLACES` -
the same precision Phase 8's own GUI shows a mark at. Excel's own numeric
type is an IEEE-754 double, so a mark whose exact value is a repeating
fraction (an eighth of a thirds-based deduction, say) is necessarily
approximated the moment it becomes an Excel number - this format keeps the
*displayed* figure consistent with what an operator already saw on the
Results stage, which is the precision Excel can actually promise, not a
claim that the workbook cell equals the stored :class:`fractions.Fraction`
bit for bit.
"""


class ExcelReportError(ReportingError):
    """A workbook could not be built. Always carries a ``user_message``.

    The `reporting` package's own error, per its documented contract
    (`reporting/__init__.py`): every failure here is a
    :class:`~omr_scanner.errors.ReportingError`.
    """


# ----------------------------------------------------------------------
# Preserving the template
# ----------------------------------------------------------------------
def copy_into(template_path: Path, output_path: Path) -> None:
    """Copy ``template_path``'s bytes to ``output_path``, unopened.

    This is the whole of how the original template is preserved (§18): a
    plain file copy, before any openpyxl call touches either path. Every
    later function in this module opens and writes only ``output_path``.

    Raises:
        ExcelReportError: The template cannot be read, or the destination
            cannot be written (a locked output file, a missing directory).
    """
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(template_path, output_path)
    except OSError as exc:
        raise ExcelReportError(
            f"Could not copy template to output: {exc}",
            user_message=(
                f"'{output_path.name}' could not be written. It may be open "
                "in Excel, or the destination folder may not be writable. "
                "Close the file or choose a different location and try again."
            ),
        ) from exc


def _open_for_writing(path: Path) -> Any:
    """Open a workbook (the *copy*, never the template) for modification."""
    try:
        import openpyxl
    except ImportError as exc:  # pragma: no cover - openpyxl is a hard dependency
        raise ExcelReportError(
            "openpyxl is not installed",
            user_message="Excel support is unavailable in this installation.",
        ) from exc
    try:
        return openpyxl.load_workbook(path)
    except Exception as exc:
        raise ExcelReportError(
            f"Copied workbook could not be reopened: {exc}",
            user_message=f"'{path.name}' could not be opened after copying.",
        ) from exc


def force_recalculation_on_load(workbook: Any) -> None:
    """Set the workbook to fully recalculate every formula when it is opened.

    Required because openpyxl - like every Python spreadsheet library -
    never evaluates the ``RANK.EQ`` formulas this module writes; without
    this, a workbook opened in a viewer that trusts cached values (some PDF
    converters, some lightweight viewers) could show stale or blank rank
    cells. Excel and LibreOffice both honour ``fullCalcOnLoad`` (§26).
    """
    from openpyxl.workbook.properties import CalcProperties

    workbook.calculation = CalcProperties(calcMode="auto", fullCalcOnLoad=True)


# ----------------------------------------------------------------------
# Rollwise
# ----------------------------------------------------------------------
@dataclass(frozen=True, slots=True)
class CandidateReportRow:
    """One candidate's effective reporting state, already decided.

    Deliberately holds *decisions*, not raw Phase 7/8 objects: this module
    must never re-derive who is absent or what a mark is, so the caller
    (:mod:`omr_scanner.services.report_store`) resolves every field from
    canonical stored data first and hands over only what is to be written.
    """

    roll: str
    is_absent: bool
    final_score: Fraction | None = None
    """``None`` for an absentee, or for a present candidate with no score yet
    (which :mod:`omr_scanner.services.report_readiness` should already have
    blocked from *final* export, but a draft/preview may still render)."""


@dataclass(frozen=True, slots=True)
class RollwiseWriteResult:
    """What actually happened writing the Rollwise sheet."""

    rows_written: int
    marks_written: int
    absent_written: int
    unresolved_rows: tuple[str, ...] = field(default_factory=tuple)
    """Rolls left blank because no decided mark was supplied for them."""


def populate_rollwise(
    output_path: Path,
    roster: TemplateRoster,
    candidates: Mapping[str, CandidateReportRow],
    *,
    marks_header_override: str | None = None,
) -> RollwiseWriteResult:
    """Fill the Rollwise sheet inside the already-copied workbook.

    Args:
        output_path: The copy made by :func:`copy_into` - never the original.
        roster: The template's own roster, in its own order.
        candidates: Every roll's decided attendance/mark, keyed by the same
            canonical Roll No. :mod:`omr_scanner.services.report_template`
            produced. A roll absent from this mapping is left exactly as the
            template had it - which for the sample means a blank marks cell.
        marks_header_override: Replacement text for the marks column header
            (§14 - a maximum score that does not match the template's own
            wording), or ``None`` to leave the template's header untouched.

    Returns:
        A summary of what was written, for the processing log.

    Never sorts, drops or inserts a row: every write is a cell assignment at
    the row the template's own :class:`~omr_scanner.services.
    report_template.TemplateRow` already named.
    """
    workbook = _open_for_writing(output_path)
    try:
        sheet = workbook[roster.sheet]
        mapping = roster.mapping

        if marks_header_override:
            sheet.cell(
                row=roster.header_row_number,
                column=mapping.marks + 1,
                value=safe_cell_text(marks_header_override),
            )

        marks_column_letter = column_letter(mapping.marks + 1)

        marks_written = 0
        absent_written = 0
        unresolved: list[str] = []

        for row in roster.rows:
            decision = candidates.get(row.roll)
            marks_cell = sheet.cell(row=row.sheet_row_number, column=mapping.marks + 1)
            rank_cell = (
                sheet.cell(row=row.sheet_row_number, column=mapping.rank + 1)
                if mapping.rank is not None
                else None
            )

            if decision is None:
                # No decision was supplied for this roll at all - typically a
                # template row that matches no registered candidate, which
                # readiness already reports separately. Leave the cell alone
                # rather than guess.
                if row.roll:
                    unresolved.append(row.roll)
                continue

            if decision.is_absent:
                marks_cell.value = ABSENT_MARK_DISPLAY
                if rank_cell is not None:
                    rank_cell.value = ABSENT_RANK_DISPLAY
                absent_written += 1
                continue

            if decision.final_score is None:
                unresolved.append(row.roll)
                continue

            marks_cell.value = float(decision.final_score)
            marks_cell.number_format = _MARK_NUMBER_FORMAT
            marks_written += 1
            if rank_cell is not None:
                rank_cell.value = rank_formula(
                    marks_column=marks_column_letter,
                    first_data_row=roster.first_data_row_number,
                    last_data_row=roster.last_data_row_number,
                    row=row.sheet_row_number,
                )

        force_recalculation_on_load(workbook)
        workbook.save(output_path)
    finally:
        workbook.close()

    _LOGGER.info(
        "Rollwise sheet populated: rows=%d marks=%d absent=%d unresolved=%d",
        len(roster.rows),
        marks_written,
        absent_written,
        len(unresolved),
    )
    return RollwiseWriteResult(
        rows_written=len(roster.rows),
        marks_written=marks_written,
        absent_written=absent_written,
        unresolved_rows=tuple(unresolved),
    )


# ----------------------------------------------------------------------
# Meritwise
#
# Built by *copying the completed Rollwise sheet* and then removing and
# reordering its rows - never by generating a fresh table. An earlier
# implementation did the latter, producing a tidy five-column listing that
# threw away the institution's heading, the post name, the column widths, the
# borders, the print setup and the logo that the Rollwise sheet had inherited
# from the office's own workbook. A merit list is the same official document
# as the roll list, in a different order.
# ----------------------------------------------------------------------


def _copy_sheet_attributes_openpyxl_drops(source: Any, copy: Any) -> None:
    """Restore what ``Workbook.copy_worksheet`` does not carry over.

    Measured against openpyxl 3.1 rather than assumed. ``copy_worksheet``
    preserves cell values and styles, merged ranges, column widths, row
    heights, page setup (orientation, paper size, fit-to-width, margins) and
    the sheet's tab colour - but silently drops the five below, every one of
    which an examination office's workbook relies on when the sheet is
    printed. ``tests/unit/test_meritwise_workbook.py`` pins each one.
    """
    copy.freeze_panes = source.freeze_panes
    copy.print_title_rows = source.print_title_rows
    copy.print_title_cols = source.print_title_cols
    if source.print_area:
        areas = source.print_area
        if isinstance(areas, str):
            areas = [areas]
        # The stored reference is qualified with the *source* sheet's name;
        # the copy needs the bare range so openpyxl re-qualifies it with its
        # own, which is why this is not a straight assignment.
        copy.print_area = ",".join(str(ref).split("!")[-1] for ref in areas)
    copy.sheet_view.showGridLines = source.sheet_view.showGridLines
    for attribute in ("oddHeader", "oddFooter", "evenHeader", "evenFooter"):
        origin = getattr(source, attribute)
        target = getattr(copy, attribute)
        for position in ("left", "center", "right"):
            getattr(target, position).text = getattr(origin, position).text


def _copy_images_onto(source: Any, copy: Any, scratch: Path) -> int:
    """Re-attach the source sheet's images to a copied sheet.

    ``copy_worksheet`` carries no drawings at all, so an institutional logo
    would vanish from the Meritwise sheet (§11 lists logos explicitly).

    Two details that are easy to get wrong, both established by experiment:

    * The image bytes are read from ``ref.getvalue()``. openpyxl's own
      ``Image._data()`` *closes* the underlying buffer, after which saving
      the workbook fails on the **original** image - so the obvious call is
      the one that must not be used here.
    * The bytes are spilled to a real file rather than kept in a
      ``BytesIO``, because openpyxl re-opens ``Image.ref`` lazily at save
      time and a buffer consumed during construction is closed by then.

    Returns:
        How many images were re-attached, for the caller's warnings.
    """
    import copy as copy_module
    import io

    from openpyxl.drawing.image import Image as ExcelImage

    attached = 0
    for index, image in enumerate(getattr(source, "_images", ())):
        reference = image.ref
        try:
            raw = (
                reference.getvalue()
                if isinstance(reference, io.BytesIO)
                else Path(str(reference)).read_bytes()
            )
        except (AttributeError, OSError):  # pragma: no cover - defensive
            continue
        spilled = scratch / f"meritwise_image_{index}.img"
        spilled.write_bytes(raw)
        try:
            fresh = ExcelImage(str(spilled))
        except Exception:
            # Pillow missing, or a format it cannot decode. The sheet is
            # still correct in every other respect, so one undecodable logo
            # must not fail the whole report; the caller reports it instead.
            continue
        fresh.width, fresh.height = image.width, image.height
        fresh.anchor = copy_module.deepcopy(image.anchor)
        copy.add_image(fresh)
        attached += 1
    return attached


def _clear_row(sheet: Any, row: int, last_column: int) -> None:
    """Blank a row's values, leaving its styling alone."""
    for column in range(1, last_column + 1):
        sheet.cell(row=row, column=column).value = None


@dataclass(frozen=True, slots=True)
class MeritwiseRow:
    """One candidate to appear on the Meritwise sheet, already ranked.

    Attributes:
        source_row_number: The 1-based row of the completed Rollwise sheet
            this candidate's row is copied from - values, styling and height
            together, so the Meritwise row looks exactly like the Rollwise
            one it came from.
        roll: For diagnostics and for the caller's own assertions.
    """

    source_row_number: int
    roll: str


@dataclass(frozen=True, slots=True)
class MeritwiseResult:
    """What building the Meritwise sheet actually did."""

    sheet_name: str
    rows_written: int
    rows_removed: int
    images_copied: int
    warnings: tuple[str, ...] = field(default_factory=tuple)


def build_meritwise_from_rollwise(
    output_path: Path,
    roster: TemplateRoster,
    ordered: Sequence[MeritwiseRow],
    *,
    serial_column: int | None = None,
    rank_column: int | None = None,
    marks_column: int | None = None,
    scratch_dir: Path | None = None,
) -> MeritwiseResult:
    """Copy the completed Rollwise sheet, drop absentees, sort by merit.

    Args:
        output_path: The workbook whose Rollwise sheet has already been
            populated. Modified in place; the *source* template is never
            touched (it was copied before any of this began).
        roster: The template roster the Rollwise sheet was written from -
            supplies the sheet name and where its data rows begin and end.
        ordered: The candidates to keep, **already in merit order**. The
            caller decides merit; this function never re-ranks, so the sheet
            and the authoritative ranking cannot disagree.
        serial_column: 1-based column holding the printed serial number,
            renumbered ``1..N`` for the merit listing, or ``None`` to leave
            whatever the Rollwise rows carried.
        rank_column: 1-based column holding Merit/Rank, rewritten as a
            ``RANK.EQ`` formula over this sheet's own row range.
        marks_column: 1-based marks column, needed only to write that
            formula.
        scratch_dir: Where image bytes are spilled while being re-attached.
            Defaults to the output workbook's own directory.

    Returns:
        A :class:`MeritwiseResult` describing what was written.

    The sheet is a **copy of the finished Rollwise sheet**, not a freshly
    built table (§10/§11): the institution's heading, the post name, the
    column widths, the borders, the print setup and the logo all come with
    it, and only the row membership and row order differ.

    Rows are rewritten rather than deleted-and-reinserted. Surplus rows at
    the end - the absentees' worth of space - are blanked and their borders
    cleared of content, which keeps every merged range, print area and
    anything printed *below* the table exactly where the template put it. A
    row deletion would move all of that up.
    """
    from openpyxl.utils import get_column_letter

    scratch = scratch_dir if scratch_dir is not None else output_path.parent
    warnings: list[str] = []

    workbook = _open_for_writing(output_path)
    try:
        source = workbook[roster.sheet]
        last_column = max(source.max_column, roster.mapping.marks + 1)

        first_data_row = roster.first_data_row_number
        last_data_row = roster.last_data_row_number

        blocking = _merges_crossing_data_rows(source, first_data_row, last_data_row)
        if blocking:
            warnings.append(
                "The template merges cells across its candidate rows "
                f"({', '.join(blocking[:3])}"
                f"{f' and {len(blocking) - 3} more' if len(blocking) > 3 else ''}); "
                "Meritwise rows were reordered without moving those merges."
            )

        # Case-insensitively, because Excel treats "Meritwise" and
        # "meritwise" as the same sheet and would refuse the rename below -
        # and because a workbook regenerated from an earlier build carries
        # the old capitalisation.
        for existing in list(workbook.sheetnames):
            if existing.casefold() == MERITWISE_SHEET_NAME.casefold():
                del workbook[existing]
        sheet = workbook.copy_worksheet(source)
        sheet.title = MERITWISE_SHEET_NAME
        _copy_sheet_attributes_openpyxl_drops(source, sheet)
        images_copied = _copy_images_onto(source, sheet, scratch)

        # The copy currently holds every Rollwise row. Rewrite the data block
        # from the top in merit order, reading each row's content out first so
        # that a row moving upward cannot overwrite one not yet copied.
        snapshot = {
            item.source_row_number: _read_row(sheet, item.source_row_number, last_column)
            for item in ordered
        }
        for offset, item in enumerate(ordered):
            target_row = first_data_row + offset
            _write_row(sheet, target_row, snapshot[item.source_row_number], last_column)
            if serial_column is not None:
                sheet.cell(row=target_row, column=serial_column, value=offset + 1)

        written_last_row = first_data_row + len(ordered) - 1
        # Clear only rows that genuinely held a candidate. A template's data
        # block routinely runs on past the last candidate - a blank spacer and
        # then "Signature of the Controller of Examinations" are read as roster
        # rows with an empty Roll No. - and blanking those would delete the
        # office's own footer from its own report.
        candidate_rows = sorted(
            row.sheet_row_number for row in roster.rows if row.roll
        )
        removed = 0
        for row in candidate_rows:
            if row > written_last_row:
                _clear_row(sheet, row, last_column)
                removed += 1

        if rank_column is not None and marks_column is not None and ordered:
            letter = get_column_letter(marks_column)
            for offset in range(len(ordered)):
                row = first_data_row + offset
                sheet.cell(
                    row=row,
                    column=rank_column,
                    value=rank_formula(
                        marks_column=letter,
                        first_data_row=first_data_row,
                        last_data_row=written_last_row,
                        row=row,
                    ),
                )

        force_recalculation_on_load(workbook)
        workbook.save(output_path)
    finally:
        workbook.close()

    return MeritwiseResult(
        sheet_name=MERITWISE_SHEET_NAME,
        rows_written=len(ordered),
        rows_removed=removed,
        images_copied=images_copied,
        warnings=tuple(warnings),
    )


def _merges_crossing_data_rows(sheet: Any, first: int, last: int) -> list[str]:
    """Merged ranges that span more than one candidate row.

    A merge inside the data block cannot survive rows being reordered, so it
    is reported rather than silently mangled. A merge in the *heading* rows -
    the usual case, an institution name across the page - does not intersect
    the data block and is left alone.
    """
    crossing: list[str] = []
    for merged in sheet.merged_cells.ranges:
        if merged.min_row > last or merged.max_row < first:
            continue
        if merged.min_row != merged.max_row:
            crossing.append(str(merged))
    return crossing


def _read_row(sheet: Any, row: int, last_column: int) -> list[tuple[object, Any, float | None]]:
    """Capture a row's values, styles and height before anything moves."""
    import copy as copy_module

    height = sheet.row_dimensions[row].height
    return [
        (
            sheet.cell(row=row, column=column).value,
            copy_module.copy(sheet.cell(row=row, column=column)._style),
            height,
        )
        for column in range(1, last_column + 1)
    ]


def _write_row(
    sheet: Any, row: int, captured: Sequence[tuple[object, Any, float | None]], last_column: int
) -> None:
    """Write back a row captured by :func:`_read_row`."""
    for index, (value, style, height) in enumerate(captured, start=1):
        if index > last_column:
            break
        cell = sheet.cell(row=row, column=index)
        cell.value = value
        cell._style = style
        if height is not None:
            sheet.row_dimensions[row].height = height


# ----------------------------------------------------------------------
# Summary
# ----------------------------------------------------------------------
@dataclass(frozen=True, slots=True)
class SummaryData:
    """Set-level report metadata (§19). ``None`` renders as ``N/A``."""

    project_name: str
    set_code: str
    registered: int
    present: int
    absent: int
    scored: int
    unresolved: int
    maximum_score: Fraction | None
    highest_score: Fraction | None
    lowest_score: Fraction | None
    mean_score: Fraction | None
    median_score: Fraction | None
    scoring_policy_summary: tuple[str, ...]
    answer_key_revision: int | None
    generated_at: datetime
    application_version: str


def add_summary_sheet(output_path: Path, data: SummaryData) -> None:
    """Add a ``Summary`` sheet: the metadata an office files alongside a result."""
    workbook = _open_for_writing(output_path)
    try:
        if SUMMARY_SHEET_NAME in workbook.sheetnames:
            del workbook[SUMMARY_SHEET_NAME]
        sheet = workbook.create_sheet(SUMMARY_SHEET_NAME)

        def _mark(value: Fraction | None) -> str:
            return format_mark(value) if value is not None else "N/A"

        rows: list[tuple[str, str]] = [
            ("Project", safe_cell_text(data.project_name)),
            ("Set", data.set_code),
            ("Registered candidates", str(data.registered)),
            ("Present", str(data.present)),
            ("Absent", str(data.absent)),
            ("Scored", str(data.scored)),
            ("Unresolved", str(data.unresolved)),
            ("Maximum possible score", _mark(data.maximum_score)),
            ("Highest obtained score", _mark(data.highest_score)),
            ("Lowest obtained score", _mark(data.lowest_score)),
            ("Mean score", _mark(data.mean_score)),
            ("Median score", _mark(data.median_score)),
            (
                "Answer-key revision",
                str(data.answer_key_revision) if data.answer_key_revision else "N/A",
            ),
            ("Generated", data.generated_at.strftime("%Y-%m-%d %H:%M:%S %Z")),
            ("Application version", data.application_version or "N/A"),
        ]
        for index, (label, value) in enumerate(rows, start=1):
            sheet.cell(row=index, column=1, value=label).font = _bold_font()
            sheet.cell(row=index, column=2, value=value)

        policy_start = len(rows) + 2
        sheet.cell(
            row=policy_start, column=1, value="Scoring configuration"
        ).font = _bold_font()
        for offset, line in enumerate(data.scoring_policy_summary, start=1):
            sheet.cell(row=policy_start + offset, column=1, value=line)

        sheet.column_dimensions["A"].width = 28
        sheet.column_dimensions["B"].width = 40
        workbook.save(output_path)
    finally:
        workbook.close()


# ----------------------------------------------------------------------
# Answer Key
# ----------------------------------------------------------------------
def add_answer_key_sheet(
    output_path: Path,
    *,
    set_code: str,
    key: AnswerKey,
    key_id: int,
) -> None:
    """Add an ``Answer Key`` sheet for **exactly this set's** stored key.

    The key handed in must already be the exact revision this set's result
    was scored under - this function writes whatever it is given and does
    not look one up, so a caller that fetched the wrong set's key would
    produce the wrong sheet with no warning here. Guarding against that is
    :mod:`omr_scanner.services.report_store`'s responsibility, verified by
    the per-set isolation tests.
    """
    workbook = _open_for_writing(output_path)
    try:
        if ANSWER_KEY_SHEET_NAME in workbook.sheetnames:
            del workbook[ANSWER_KEY_SHEET_NAME]
        sheet = workbook.create_sheet(ANSWER_KEY_SHEET_NAME)
        sheet.cell(
            row=1, column=1, value=f"Set {set_code} - Answer Key"
        ).font = _bold_font(size=12)
        sheet.cell(row=2, column=1, value=f"Revision {key.revision} (id {key_id})")
        sheet.cell(row=3, column=1, value=f"Canonical string: {key.answers}")

        header_row = 5
        sheet.cell(row=header_row, column=1, value="Q No.").font = _bold_font()
        sheet.cell(row=header_row, column=2, value="Correct Answer").font = _bold_font()
        sheet.cell(row=header_row, column=3, value="Wrong Question").font = _bold_font()
        for offset, number in enumerate(key.question_numbers):
            row = header_row + 1 + offset
            sheet.cell(row=row, column=1, value=number)
            sheet.cell(row=row, column=2, value=key.answer_for(number))
            sheet.cell(
                row=row, column=3, value="Yes" if key.is_wrong_question(number) else ""
            )
        for column, width in ((1, 10), (2, 16), (3, 16)):
            sheet.column_dimensions[column_letter(column)].width = width
        workbook.save(output_path)
    finally:
        workbook.close()


# ----------------------------------------------------------------------
# Processing Log
# ----------------------------------------------------------------------
@dataclass(frozen=True, slots=True)
class ProcessingLogEntry:
    """One line of the generation audit - counts and hashes, never a name."""

    label: str
    value: str


def add_processing_log_sheet(
    output_path: Path, entries: Sequence[ProcessingLogEntry]
) -> None:
    """Add a ``Processing Log`` sheet: the generation audit, not a data dump.

    Every entry here must already have been through
    :mod:`omr_scanner.services.report_store`'s privacy discipline - this
    function writes exactly what it is given and performs no filtering of
    its own, so a caller that hands it a candidate name would put one in the
    workbook. It never does, by construction: see the callers in
    ``services/report_store.py``.
    """
    workbook = _open_for_writing(output_path)
    try:
        if PROCESSING_LOG_SHEET_NAME in workbook.sheetnames:
            del workbook[PROCESSING_LOG_SHEET_NAME]
        sheet = workbook.create_sheet(PROCESSING_LOG_SHEET_NAME)
        sheet.append(["Field", "Value"])
        for cell in sheet[1]:
            cell.font = _bold_font()
        for entry in entries:
            sheet.append([entry.label, entry.value])
        sheet.column_dimensions["A"].width = 28
        sheet.column_dimensions["B"].width = 60
        workbook.save(output_path)
    finally:
        workbook.close()


# ----------------------------------------------------------------------
# Layout: header text, logo, page setup
# ----------------------------------------------------------------------
@dataclass(frozen=True, slots=True)
class LayoutSettings:
    """Everything an operator can configure about a report's presentation.

    Mirrors :class:`omr_scanner.database.models.ReportLayoutConfig` field for
    field; kept as a separate plain dataclass here so this module never
    imports SQLAlchemy.
    """

    title_text: str = ""
    subtitle_text: str = ""
    examination_name: str = ""
    footer_text: str = ""
    column_header_overrides: Mapping[str, str] = field(default_factory=dict)
    auto_update_marks_header: bool = True
    logo_path: str = ""
    logo_max_width_px: int = 120
    logo_max_height_px: int = 120
    font_family: str = ""
    title_font_size: int = 14
    header_font_size: int = 11
    body_font_size: int = 10
    bold_headers: bool = True
    page_size: str = "A4"
    orientation: str = "portrait"
    margin_top_mm: float = 20.0
    margin_bottom_mm: float = 20.0
    margin_left_mm: float = 20.0
    margin_right_mm: float = 20.0
    fit_to_width: bool = True
    scale_percent: int = 100
    center_horizontally: bool = True
    repeat_header_row: bool = True

    @classmethod
    def from_json(cls, payload: str) -> LayoutSettings:
        """Reconstruct settings from :meth:`to_json`'s output."""
        data = json.loads(payload) if payload else {}
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})

    def to_json(self) -> str:
        """Serialise for a ``GeneratedReport.layout_config_snapshot_json`` cell."""
        return json.dumps(
            {
                name: (
                    dict(getattr(self, name))
                    if isinstance(getattr(self, name), Mapping)
                    else getattr(self, name)
                )
                for name in self.__dataclass_fields__
            },
            ensure_ascii=False,
            sort_keys=True,
        )


_MM_PER_INCH = 25.4
_PAGE_SIZE_MAP = {"A4": "A4", "LETTER": "letter"}


def apply_layout(
    output_path: Path,
    sheet_names: Sequence[str],
    layout: LayoutSettings,
    *,
    primary_header_row: int,
) -> tuple[str, ...]:
    """Apply page setup, and header text/logo where space allows.

    Args:
        output_path: The workbook to modify.
        sheet_names: Which sheets get the page-setup treatment (typically
            Rollwise and Meritwise - Summary/Answer Key/Processing Log are
            working documents, not print-formatted pages).
        layout: The configured settings.
        primary_header_row: The **already-known** 1-based header row of the
            primary (first-listed) sheet - the same
            :attr:`~omr_scanner.services.report_template.TemplateRoster.header_row_number`
            the roster was read with. Title/logo placement never re-detects
            this: a template with decorative rows containing text of their
            own (the common case this feature is for) would make a "first
            non-blank row" heuristic pick the decorative row itself as the
            header, believing there is no blank space left at all.

    Returns:
        Warnings that do not stop generation - most notably, "there was no
        blank space above the header to add a title without disturbing
        candidate rows", which the phase brief's "never automatically append
        or delete a candidate row" rule (§8) makes an absolute constraint
        rather than something this function may work around by shifting rows.

    Layout preservation is the default (§16, §17): every field left at its
    default (empty text, no logo) changes nothing, so a template with its
    own header, its own logo and its own print setup is untouched unless the
    operator explicitly asks for something different.
    """
    workbook = _open_for_writing(output_path)
    warnings: list[str] = []
    try:
        for name in sheet_names:
            if name not in workbook.sheetnames:
                continue
            sheet = workbook[name]
            _apply_page_setup(sheet, layout)
            if name == sheet_names[0]:
                # Header/logo insertion only ever targets the primary
                # (Rollwise) sheet - it is the one page the phase brief
                # describes as "the official result", and repeating a title
                # into every generated sheet risks the same row-shifting
                # problem this function exists to avoid, sheet by sheet.
                warnings.extend(
                    _apply_header_and_logo(sheet, layout, header_row=primary_header_row)
                )
        workbook.save(output_path)
    finally:
        workbook.close()
    return tuple(warnings)


def _apply_page_setup(sheet: Any, layout: LayoutSettings) -> None:
    """Page size, orientation, margins, scaling and the repeating header row."""
    sheet.page_setup.paperSize = (
        sheet.PAPERSIZE_A4
        if layout.page_size.upper() != "LETTER"
        else sheet.PAPERSIZE_LETTER
    )
    sheet.page_setup.orientation = (
        "landscape" if layout.orientation.lower() == "landscape" else "portrait"
    )
    sheet.page_margins.top = layout.margin_top_mm / _MM_PER_INCH
    sheet.page_margins.bottom = layout.margin_bottom_mm / _MM_PER_INCH
    sheet.page_margins.left = layout.margin_left_mm / _MM_PER_INCH
    sheet.page_margins.right = layout.margin_right_mm / _MM_PER_INCH
    if layout.fit_to_width:
        sheet.sheet_properties.pageSetUpPr.fitToPage = True
        sheet.page_setup.fitToWidth = 1
        sheet.page_setup.fitToHeight = 0
    else:
        sheet.page_setup.scale = max(10, min(400, layout.scale_percent))
    sheet.print_options.horizontalCentered = layout.center_horizontally
    if layout.repeat_header_row:
        sheet.print_title_rows = "1:1"


def _apply_header_and_logo(
    sheet: Any, layout: LayoutSettings, *, header_row: int
) -> list[str]:
    """Insert title/subtitle/logo into blank rows above the header, if any.

    Never shifts a row. If the operator configured a title but the template
    leaves no blank row above its header, the title is skipped and a warning
    is returned rather than the candidate table being disturbed.
    """
    warnings: list[str] = []
    available = header_row - 1

    wanted_text_rows = sum(
        1 for text in (layout.title_text, layout.subtitle_text, layout.examination_name)
        if text
    )
    if wanted_text_rows and available < wanted_text_rows:
        warnings.append(
            "The report title could not be added: this template has no "
            f"blank row above its header ({available} available, "
            f"{wanted_text_rows} needed). Add blank rows above the header "
            "in the template, or leave the title unset."
        )
    else:
        row = 1
        for text, size in (
            (layout.title_text, layout.title_font_size),
            (layout.examination_name, layout.header_font_size),
            (layout.subtitle_text, layout.body_font_size),
        ):
            if not text:
                continue
            from openpyxl.styles import Font

            cell = sheet.cell(row=row, column=1, value=safe_cell_text(text))
            font_kwargs: dict[str, Any] = {"size": size, "bold": row == 1}
            if layout.font_family:
                font_kwargs["name"] = layout.font_family
            cell.font = Font(**font_kwargs)
            row += 1

    if layout.logo_path:
        warnings.extend(_insert_logo(sheet, layout))

    return warnings


def _insert_logo(sheet: Any, layout: LayoutSettings) -> list[str]:
    """Insert a size-constrained, aspect-preserved logo image, best-effort.

    Failure here (a missing Pillow installation, an unreadable image file)
    degrades to a warning, never a failed generation - a report without its
    logo is still a usable, correct result; one that failed to generate at
    all because of a decorative image is not an acceptable trade.
    """
    from pathlib import Path as _Path

    logo_file = _Path(layout.logo_path)
    if not logo_file.is_file():
        return [f"Logo file not found: {logo_file.name}. The logo was skipped."]
    try:
        from openpyxl.drawing.image import Image as XLImage
    except ImportError:
        return [
            "The logo could not be embedded because image support "
            "(Pillow) is not installed. The logo was skipped."
        ]
    try:
        image = XLImage(str(logo_file))
        original_width, original_height = image.width, image.height
        if not original_width or not original_height:
            raise ValueError("image reports zero size")
        scale = min(
            layout.logo_max_width_px / original_width,
            layout.logo_max_height_px / original_height,
            1.0,
        )
        image.width = max(1, round(original_width * scale))
        image.height = max(1, round(original_height * scale))
        # Anchored beside the header text rather than over it - never on top
        # of a candidate row, and never resized without keeping the aspect
        # ratio computed above.
        anchor_column = max(1, sheet.max_column - 1)
        image.anchor = f"{column_letter(anchor_column)}1"
        sheet.add_image(image)
        return []
    except Exception as exc:
        # Any failure here degrades to a warning, never a crash - see the
        # function's own docstring.
        return [f"The logo could not be embedded ({exc}). The logo was skipped."]
