"""Application workflows.

Purpose:
    Coordinate domain models, the database, imaging, recognition and reporting
    into the operations a user actually performs ("create a project", "process a
    batch of scans", "calculate results").

Responsibilities:
    * Own multi-step operations and their failure handling.
    * Translate low-level failures into :mod:`omr_scanner.errors` exceptions the
      GUI can present.
    * Perform file system and database side effects; the domain layer never does.

What does NOT belong here:
    * Widgets, dialogs, Qt signals or any other presentation concern. A service
      must be callable from a test, a script or a future command line tool.
    * Image-processing algorithms (``imaging``) and value interpretation
      (``recognition``); services *call* those, they do not implement them.

Phase status:
    Phase 0 implements :mod:`omr_scanner.services.project_service` and
    :mod:`omr_scanner.services.template_service`; Phase 1 adds
    :mod:`omr_scanner.services.alignment_service`, the boundary that hands a
    template's geometry to the imaging layer. Phase 3 adds the scan workflow:
    :mod:`omr_scanner.services.recognition_service` (one sheet, end to end),
    :mod:`omr_scanner.services.batch_processor` (many of them, with progress and
    per-file error isolation), :mod:`omr_scanner.services.parallel_batch` (the
    worker-process pool that reads several sheets at once),
    :mod:`omr_scanner.services.filename_manager`
    (collision-free output names), :mod:`omr_scanner.services.scan_import`
    (what the user selected) and :mod:`omr_scanner.services.scan_export` (the
    results CSV). Conflict, attendance, scoring and Excel/PDF reporting services
    arrive with their own phases (see ``development/ROADMAP.md``).
"""

# Phase 7 modules are exposed as modules rather than as fifty loose names: the
# reconciliation surface is large, and `reconciliation_store.assign_script(...)`
# reads better at a call site than an unqualified `assign_script(...)`.
from omr_scanner.services import (
    answer_key,
    candidate_import,
    diagnostics,
    process_containment,
    project_backup,
    project_health,
    project_sets,
    reconciliation,
    reconciliation_store,
    report_readiness,
    report_store,
    report_template,
    scan_provenance,
    scoring,
    scoring_store,
    telemetry,
)
from omr_scanner.services.alignment_service import (
    alignment_config_from_template,
    load_scan_image,
    save_image,
)
from omr_scanner.services.answer_key import (
    AnswerKeyError,
    QuestionPlan,
    key_from_scan,
    plan_for,
    read_key,
)
from omr_scanner.services.batch_processor import (
    BatchOptions,
    BatchProgress,
    BatchReport,
    BatchStage,
    ProcessedScan,
    finalise_scan,
    plan_output_name,
    process_batch,
    process_scan,
)
from omr_scanner.services.batch_progress import (
    BatchProgressTracker,
    BatchState,
    JobStatus,
    ProgressSnapshot,
    format_count,
    format_duration,
    format_rate,
)
from omr_scanner.services.batch_store import (
    BatchIdentity,
    BatchRecorder,
    BatchStatus,
    BatchSummary,
    CompatibilityVerdict,
    ErrorCategory,
    ScanJobStatus,
    categorise_error,
    check_compatibility,
    completed_results,
    create_batch,
    delete_batch,
    failed_scans,
    finalise_batch,
    list_batches,
    load_summary,
    mark_cancelled,
    mark_queued,
    record_results,
    recover_interrupted,
    results_by_scan,
    resumable_scans,
    scan_ids_by_path,
    scan_paths,
    set_batch_status,
)
from omr_scanner.services.calibration_service import (
    CalibrationFinding,
    CalibrationReport,
    CalibrationSampleReport,
    CalibrationStatus,
    aggregate_calibration,
    apply_calibration,
    evaluate_calibration,
    separation_label,
    write_calibration_report,
)
from omr_scanner.services.candidate_import import (
    CandidateImportError,
    ColumnMapping,
    RosterValidation,
    normalise_candidate_id,
    preview_roster,
    read_roster,
    save_sample_template,
)
from omr_scanner.services.conflict_policy import (
    ConflictPolicy,
    DetectedConflict,
    describe_template_choices,
    detect_conflicts,
    detect_duplicate_identifiers,
    group_cells,
    group_labels,
)
from omr_scanner.services.filename_manager import (
    FilenameAllocator,
    duplicate_suffix,
    sanitise_stem,
)
from omr_scanner.services.marker_detection_service import (
    ORIENTATION_DEBUG_IMAGE_NAME,
    DecodedImage,
    DetectedMarker,
    MarkerDetectionOutcome,
    MarkerSearchConfig,
    OrientationDetectionOutcome,
    OrientationSearchConfig,
    decode_image_file,
    detect_orientation_marker_in_region,
    detect_registration_markers,
)
from omr_scanner.services.project_service import (
    ProjectDatabase,
    ProjectSession,
    create_project,
    is_project_directory,
    open_project,
    read_project_metadata,
    update_exam_name,
)
from omr_scanner.services.recognition_diagnostics import (
    render_overlay,
    write_diagnostics,
)
from omr_scanner.services.recognition_models import (
    ENGINE_NAME,
    ENGINE_VERSION,
    RESULT_SCHEMA_VERSION,
    AnswerView,
    BubbleView,
    CharacterView,
    FieldView,
    MarkerView,
    RecognitionOutcome,
    RegistrationStatus,
    ScanQuality,
    ScanResult,
    StageTimings,
    StatusCode,
    ZoneView,
)
from omr_scanner.services.recognition_service import (
    CalibrationSession,
    RecognitionEngine,
    map_canonical_to_source,
    recognise_scan,
)
from omr_scanner.services.recognition_settings import (
    DiagnosticsOptions,
    RecognitionOptions,
)
from omr_scanner.services.reconciliation import ReconciliationInput, reconcile
from omr_scanner.services.reconciliation_store import ReconciliationError
from omr_scanner.services.review_store import (
    AuditRecord,
    ConflictFilter,
    ConflictRecord,
    EffectiveIdentifier,
    ReviewError,
    accept_machine_value,
    correct_value,
    count_conflicts,
    count_conflicts_for_scan,
    defer,
    effective_identifiers,
    effective_values_for_scan,
    get_conflict,
    history_for,
    list_conflicts,
    provenance_for,
    recompute_state,
    reopen,
    scan_source_path,
    sheet_resolutions,
    sync_conflicts,
    sync_duplicate_identifiers,
    validate_reason,
    validate_reviewer,
)
from omr_scanner.services.scan_export import (
    EMPTY_RESOLUTION,
    SheetResolution,
    export_scan_results,
    render_scan_results,
)
from omr_scanner.services.scan_import import (
    SUPPORTED_SCAN_SUFFIXES,
    collect_scan_files,
    is_supported_scan,
    natural_sort_key,
)
from omr_scanner.services.scoring import (
    CandidateAnswers,
    build_candidate_answers,
    score_candidate,
)
from omr_scanner.services.scoring_store import ScoringError
from omr_scanner.services.template_service import (
    list_templates,
    load_template,
    save_template,
)

__all__ = [
    "EMPTY_RESOLUTION",
    "ENGINE_NAME",
    "ENGINE_VERSION",
    "ORIENTATION_DEBUG_IMAGE_NAME",
    "RESULT_SCHEMA_VERSION",
    "SUPPORTED_SCAN_SUFFIXES",
    "AnswerKeyError",
    "AnswerView",
    "AuditRecord",
    "BatchIdentity",
    "BatchOptions",
    "BatchProgress",
    "BatchProgressTracker",
    "BatchRecorder",
    "BatchReport",
    "BatchStage",
    "BatchState",
    "BatchStatus",
    "BatchSummary",
    "BubbleView",
    "CalibrationFinding",
    "CalibrationReport",
    "CalibrationSampleReport",
    "CalibrationSession",
    "CalibrationStatus",
    "CandidateAnswers",
    "CandidateImportError",
    "CharacterView",
    "ColumnMapping",
    "CompatibilityVerdict",
    "ConflictFilter",
    "ConflictPolicy",
    "ConflictRecord",
    "DecodedImage",
    "DetectedConflict",
    "DetectedMarker",
    "DiagnosticsOptions",
    "EffectiveIdentifier",
    "ErrorCategory",
    "FieldView",
    "FilenameAllocator",
    "JobStatus",
    "MarkerDetectionOutcome",
    "MarkerSearchConfig",
    "MarkerView",
    "OrientationDetectionOutcome",
    "OrientationSearchConfig",
    "ProcessedScan",
    "ProgressSnapshot",
    "ProjectDatabase",
    "ProjectSession",
    "QuestionPlan",
    "RecognitionEngine",
    "RecognitionOptions",
    "RecognitionOutcome",
    "ReconciliationError",
    "ReconciliationInput",
    "RegistrationStatus",
    "ReviewError",
    "RosterValidation",
    "ScanJobStatus",
    "ScanQuality",
    "ScanResult",
    "ScoringError",
    "SheetResolution",
    "StageTimings",
    "StatusCode",
    "ZoneView",
    "accept_machine_value",
    "aggregate_calibration",
    "alignment_config_from_template",
    "answer_key",
    "apply_calibration",
    "build_candidate_answers",
    "candidate_import",
    "categorise_error",
    "check_compatibility",
    "collect_scan_files",
    "completed_results",
    "correct_value",
    "count_conflicts",
    "count_conflicts_for_scan",
    "create_batch",
    "create_project",
    "decode_image_file",
    "defer",
    "delete_batch",
    "describe_template_choices",
    "detect_conflicts",
    "detect_duplicate_identifiers",
    "detect_orientation_marker_in_region",
    "detect_registration_markers",
    "diagnostics",
    "duplicate_suffix",
    "effective_identifiers",
    "effective_values_for_scan",
    "evaluate_calibration",
    "export_scan_results",
    "failed_scans",
    "finalise_batch",
    "finalise_scan",
    "format_count",
    "format_duration",
    "format_rate",
    "get_conflict",
    "group_cells",
    "group_labels",
    "history_for",
    "is_project_directory",
    "is_supported_scan",
    "key_from_scan",
    "list_batches",
    "list_conflicts",
    "list_templates",
    "load_scan_image",
    "load_summary",
    "load_template",
    "map_canonical_to_source",
    "mark_cancelled",
    "mark_queued",
    "natural_sort_key",
    "normalise_candidate_id",
    "open_project",
    "plan_for",
    "plan_output_name",
    "preview_roster",
    "process_batch",
    "process_containment",
    "process_scan",
    "project_backup",
    "project_health",
    "project_sets",
    "provenance_for",
    "read_key",
    "read_project_metadata",
    "read_roster",
    "recognise_scan",
    "recompute_state",
    "reconcile",
    "reconciliation",
    "reconciliation_store",
    "record_results",
    "recover_interrupted",
    "render_overlay",
    "render_scan_results",
    "reopen",
    "report_readiness",
    "report_store",
    "report_template",
    "results_by_scan",
    "resumable_scans",
    "sanitise_stem",
    "save_image",
    "save_sample_template",
    "save_template",
    "scan_ids_by_path",
    "scan_paths",
    "scan_provenance",
    "scan_source_path",
    "score_candidate",
    "scoring",
    "scoring_store",
    "separation_label",
    "set_batch_status",
    "sheet_resolutions",
    "sync_conflicts",
    "sync_duplicate_identifiers",
    "telemetry",
    "update_exam_name",
    "validate_reason",
    "validate_reviewer",
    "write_calibration_report",
    "write_diagnostics",
]
