"""Store answer keys, scoring policy and results - and recompute, never patch.

Purpose:
    The repository layer for Phase 8: answer-key revisions and their
    verification, scoring-policy revisions, and `CandidateResult` rows that
    identify exactly which of each produced them.

Scope:
    Database access. The arithmetic is in :mod:`omr_scanner.domain.scoring`,
    the eligibility rules in :mod:`omr_scanner.services.scoring`, and neither
    imports Qt.

Three arrangements that carry the phase:

**A revision is never edited.** Correcting a verified key that results already
reference creates the next revision and supersedes the old one; the old row
stays, because a result points at it. The same is true of the scoring policy.

**A result stores its inputs, not just its mark.** The answer string, the key
revision and the policy revision are all on the row, so the breakdown can be
regenerated by the same pure function that produced the total - which is why
there is no per-question table to fall out of step with it.

**Changing an input makes a result stale; it never changes the number.**
:func:`stale_reasons_for` compares what a result was computed from against what
is current, and :func:`score_batch` runs the whole scorer again from stored
inputs. Nothing in this module adds a delta to an existing mark.

Privacy:
    No candidate ID, name, answer string or mark is logged. Counts, revisions
    and roster/batch ids only - see ``docs/reconciliation.md`` §9.
"""

from __future__ import annotations

import json
import logging
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from fractions import Fraction
from typing import TYPE_CHECKING, Any

from sqlalchemy import delete, func, select

from omr_scanner.database.models import (
    AnswerKeyRevision,
    CandidateResult,
    ScoringPolicyRevision,
)
from omr_scanner.domain.reconciliation import AttendanceState
from omr_scanner.domain.scoring import (
    AnswerKey,
    AnswerKeySource,
    AnswerKeyStatus,
    BlockReason,
    NegativeMarking,
    ResultCounts,
    ResultStatus,
    ScoreBreakdown,
    ScoringBlock,
    ScoringPolicy,
    StaleReason,
    score_answers,
)
from omr_scanner.errors import OMRScannerError
from omr_scanner.services import (
    project_sets,
    reconciliation_store,
    session_population,
    set_identity,
)
from omr_scanner.services.answer_key import QuestionPlan, compatibility_issues, plan_for
from omr_scanner.services.scoring import (
    CandidateAnswers,
    CandidateScore,
    ScoringInputs,
    build_candidate_answers,
    score_candidate,
    working_script,
)
from omr_scanner.services.set_identity import (
    SetCodeMap,
    canonical_code,
    distinct_codes,
    group_by_set,
    same_set,
)

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping, Sequence

    from sqlalchemy.orm import Session

    from omr_scanner.database.engine import ProjectDatabase
    from omr_scanner.domain.reconciliation import ReconciliationEntry
    from omr_scanner.domain.template import OmrTemplate
    from omr_scanner.services.recognition_models import ScanResult

_LOGGER = logging.getLogger(__name__)


class ScoringError(OMRScannerError):
    """A scoring or answer-key operation was refused.

    Always carries a ``user_message``: an operator is mid-task and needs to
    know what to do differently.
    """


def _now() -> datetime:
    """The current instant, timezone-aware."""
    return datetime.now(UTC)


def _dump_numbers(numbers: Iterable[int]) -> str:
    """Serialise a set of question numbers for storage."""
    return ",".join(str(number) for number in sorted(set(numbers)))


def _load_numbers(payload: str) -> frozenset[int]:
    """Read a stored set of question numbers."""
    return frozenset(
        int(chunk) for chunk in payload.split(",") if chunk.strip().isdigit()
    )


# ----------------------------------------------------------------------
# Answer keys
# ----------------------------------------------------------------------
def _to_key(row: AnswerKeyRevision) -> AnswerKey:
    """Convert a stored revision into a detached domain key."""
    return AnswerKey(
        set_code=row.set_code,
        answers=row.answers,
        wrong_questions=_load_numbers(row.wrong_questions),
        revision=row.revision,
        first_question=row.first_question,
        status=AnswerKeyStatus(row.status),
        source=AnswerKeySource(row.source),
    )


@dataclass(frozen=True, slots=True)
class StoredKey:
    """One answer-key revision, with the row id a result references.

    The provenance fields (``created_by`` onward) are empty on a revision
    stored before migration 12; nothing fills them in retrospectively.
    """

    key_id: int
    key: AnswerKey
    created_at: datetime
    verified_at: datetime | None = None
    verified_by: str = ""
    source_scan: str = ""
    notes: str = ""
    created_by: str = ""
    template_id: str = ""
    template_name: str = ""
    template_fingerprint: str = ""
    source_sha256: str = ""
    source_metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def set_code(self) -> str:
        """Which paper this answers."""
        return self.key.set_code

    @property
    def revision(self) -> int:
        """Which revision this is."""
        return self.key.revision

    def describe(self) -> str:
        """A one-line summary for a list."""
        return self.key.describe()


def _load_metadata(payload: str) -> dict[str, Any]:
    """Read a stored metadata blob; a damaged one reads as empty, never raises."""
    if not payload:
        return {}
    try:
        value = json.loads(payload)
    except ValueError:
        return {}
    return value if isinstance(value, dict) else {}


def _stored(row: AnswerKeyRevision) -> StoredKey:
    return StoredKey(
        key_id=row.key_id,
        key=_to_key(row),
        created_at=row.created_at,
        verified_at=row.verified_at,
        verified_by=row.verified_by,
        source_scan=row.source_scan,
        notes=row.notes,
        created_by=row.created_by,
        template_id=row.template_id,
        template_name=row.template_name,
        template_fingerprint=row.template_fingerprint,
        source_sha256=row.source_sha256,
        source_metadata=_load_metadata(row.source_metadata_json),
    )


def save_key(
    database: ProjectDatabase,
    key: AnswerKey,
    *,
    source_scan: str = "",
    notes: str = "",
    created_by: str = "",
    template: OmrTemplate | None = None,
    source_sha256: str = "",
    source_metadata: dict[str, Any] | None = None,
) -> StoredKey:
    """Store a new draft revision of a set's answer key.

    Args:
        database: The open project database.
        key: The key to store. Its ``revision`` is **ignored** and recomputed -
            the store owns revision numbering, so two operators cannot create
            two "revision 2"s.
        source_scan: The solution sheet's file name, when the key was read from
            one. A name, not a path.
        notes: Free text.
        created_by: Who entered or imported the key.
        template: The template the key was written against; its id, name and
            geometry fingerprint are recorded so a later template change can be
            recognised.
        source_sha256: SHA-256 of the solution-sheet image, when there is one.
            Recorded because the file may later be moved or deleted.
        source_metadata: JSON-serialisable facts about how a scanned key was
            read (registration, set-code check, questions corrected by hand).

    Returns:
        The stored revision, with the id a result will reference.

    A new revision is always created. Editing a stored revision in place would
    silently change what an existing result was computed from, which is the one
    thing Phase 8 must never do.

    Revisions are numbered per **logical** set: a revision stored earlier under
    ``"a"`` and one stored now under ``"A"`` are revisions 1 and 2 of one set.
    The code is stored as given; it is compared canonically.
    """
    with database.session() as session:
        highest = max(
            (
                int(revision)
                for code, revision in session.execute(
                    select(AnswerKeyRevision.set_code, AnswerKeyRevision.revision)
                ).all()
                if same_set(code, key.set_code)
            ),
            default=0,
        )
        revision = highest + 1
        row = AnswerKeyRevision(
            set_code=key.set_code,
            revision=revision,
            answers=key.answers,
            wrong_questions=_dump_numbers(key.wrong_questions),
            first_question=key.first_question,
            question_count=key.question_count,
            status=AnswerKeyStatus.DRAFT.value,
            source=key.source.value,
            source_scan=source_scan,
            notes=notes,
            created_at=_now(),
            created_by=created_by.strip(),
            template_id=template.template_id if template is not None else "",
            template_name=template.name if template is not None else "",
            template_fingerprint=(
                template.geometry_fingerprint() if template is not None else ""
            ),
            source_sha256=source_sha256,
            source_metadata_json=(
                json.dumps(source_metadata, sort_keys=True) if source_metadata else ""
            ),
        )
        session.add(row)
        session.flush()
        stored = _stored(row)

    _LOGGER.info(
        "Answer key saved: set=%s revision=%d questions=%d wrong=%d source=%s",
        key.set_code,
        revision,
        key.question_count,
        len(key.wrong_questions),
        key.source.value,
    )
    return stored


def verify_key(
    database: ProjectDatabase,
    key_id: int,
    *,
    verified_by: str,
    plan: QuestionPlan | None = None,
) -> StoredKey:
    """Mark one revision verified, superseding the set's previous verified one.

    Args:
        database: The open project database.
        key_id: The revision to verify.
        verified_by: Who checked it. Required - a key is the standard every
            candidate is measured against, and an unattributed one is not a
            standard.
        plan: The active template's questions. When given, a revision that no
            longer fits it (see
            :func:`~omr_scanner.services.answer_key.compatibility_issues`) is
            refused: verifying a key for a different paper would let it mark
            candidates.

    Raises:
        ScoringError: No such revision, no name given, the revision is already
            superseded, or it does not fit ``plan``.

    Superseding rather than deleting: results computed under the previous
    revision still point at it, and must still be able to say what they were
    computed from.
    """
    name = verified_by.strip()
    if not name:
        raise ScoringError(
            "No verifier name",
            user_message=(
                "Set your name in File > Settings > Reviewer before verifying "
                "an answer key. A verified key is recorded against the person "
                "who checked it."
            ),
        )
    identity = set_identity.load(database)
    with database.session() as session:
        row = session.get(AnswerKeyRevision, key_id)
        if row is None:
            raise ScoringError(
                f"Answer key {key_id} not found",
                user_message="That answer key is no longer in this project.",
            )
        if row.status == AnswerKeyStatus.SUPERSEDED.value:
            raise ScoringError(
                "Refusing to verify a superseded revision",
                user_message=(
                    f"Set {row.set_code} revision {row.revision} has been "
                    "replaced by a later revision and cannot be verified again."
                ),
            )
        if plan is not None:
            problems = compatibility_issues(_to_key(row), plan)
            if problems:
                raise ScoringError(
                    "Refusing to verify a key that does not fit the template",
                    user_message=(
                        f"Set {row.set_code} revision {row.revision} does not fit "
                        f"the active template: {problems[0]}"
                    ),
                )
        set_identity.require_no_collision(
            identity, purpose="Verifying this answer key", codes=(row.set_code,)
        )
        for other in session.scalars(
            select(AnswerKeyRevision)
            .where(AnswerKeyRevision.status == AnswerKeyStatus.VERIFIED.value)
            .where(AnswerKeyRevision.key_id != key_id)
        ).all():
            # One verified revision per *logical* set, whatever spelling an
            # earlier revision was stored under.
            if same_set(other.set_code, row.set_code):
                other.status = AnswerKeyStatus.SUPERSEDED.value
        row.status = AnswerKeyStatus.VERIFIED.value
        row.verified_at = _now()
        row.verified_by = name
        stored = _stored(row)

    _LOGGER.info(
        "Answer key verified: set=%s revision=%d", stored.set_code, stored.revision
    )
    return stored


def verified_key(database: ProjectDatabase, set_code: str) -> StoredKey | None:
    """Return the verified key for one set, or ``None``.

    Compared canonically, so a key stored as ``"a"`` is Set ``A``'s - the
    lookup that once upper-cased only one side (defect 5 of
    ``0.1.0-alpha.2``).
    """
    return verified_keys(database).get(set_code)


def verified_keys(database: ProjectDatabase) -> SetCodeMap[StoredKey]:
    """Return every set's verified key, keyed by set code, compared canonically.

    ``keys.get("a")`` finds a key stored under ``"A"``. Should two verified
    revisions of one logical set exist - possible only in data written before
    canonical identity, under two spellings - the most recently verified wins
    and the other is listed in :attr:`~omr_scanner.domain.set_identity.SetCodeMap.shadowed`;
    :func:`verify_key` now supersedes across spellings, so it cannot recur.
    """
    with database.session() as session:
        rows = session.scalars(
            select(AnswerKeyRevision)
            .where(AnswerKeyRevision.status == AnswerKeyStatus.VERIFIED.value)
            .order_by(
                AnswerKeyRevision.verified_at.desc(),
                AnswerKeyRevision.revision.desc(),
                AnswerKeyRevision.key_id.desc(),
            )
        ).all()
        found = SetCodeMap((row.set_code, _stored(row)) for row in rows)
    # Iterated in set-code order, as the dictionary this replaces was.
    return SetCodeMap((code, found[code]) for code in sorted(found))


def get_key(database: ProjectDatabase, key_id: int) -> StoredKey | None:
    """Return one revision by id, whatever its status."""
    with database.session() as session:
        row = session.get(AnswerKeyRevision, key_id)
        return _stored(row) if row is not None else None


def list_keys(
    database: ProjectDatabase, *, set_code: str = ""
) -> tuple[StoredKey, ...]:
    """Return stored revisions, newest first, optionally for one set (canonically)."""
    with database.session() as session:
        rows = session.scalars(
            select(AnswerKeyRevision).order_by(
                AnswerKeyRevision.set_code, AnswerKeyRevision.revision.desc()
            )
        ).all()
        wanted = set_code.strip()
        return tuple(
            _stored(row) for row in rows if not wanted or same_set(row.set_code, wanted)
        )


def known_set_codes(database: ProjectDatabase) -> tuple[str, ...]:
    """Every set a key has been written for, one spelling per logical set."""
    with database.session() as session:
        return distinct_codes(
            sorted(
                {
                    value
                    for (value,) in session.execute(
                        select(AnswerKeyRevision.set_code).distinct()
                    ).all()
                }
            )
        )


class SetKeyState(StrEnum):
    """Whether one set has a key Results can mark with."""

    MISSING = "missing"
    """No revision has ever been stored for the set."""

    DRAFT = "draft"
    """Revisions exist, none verified. Results will not mark with it."""

    VERIFIED = "verified"
    """A verified revision that fits the active template."""

    STALE = "stale"
    """The revision that would be used no longer fits the active template."""

    @property
    def label(self) -> str:
        """Operator-facing wording."""
        return {
            SetKeyState.MISSING: "Missing",
            SetKeyState.DRAFT: "Draft",
            SetKeyState.VERIFIED: "Verified",
            SetKeyState.STALE: "Incompatible",
        }[self]


@dataclass(frozen=True, slots=True)
class SetKeyOverview:
    """One set's answer-key position, for the overview and the pre-Results check.

    Attributes:
        set_code: The set.
        state: See :class:`SetKeyState`.
        verified: The verified revision - the one Results marks with - if any.
        latest: The newest revision, whatever its status.
        issues: Why the revision that would be used does not fit the template.
    """

    set_code: str
    state: SetKeyState
    verified: StoredKey | None = None
    latest: StoredKey | None = None
    issues: tuple[str, ...] = ()

    @property
    def has_pending_draft(self) -> bool:
        """Whether a draft newer than the verified revision is waiting."""
        return (
            self.latest is not None
            and self.latest.key.status is AnswerKeyStatus.DRAFT
            and (self.verified is None or self.latest.revision > self.verified.revision)
        )

    @property
    def is_ready(self) -> bool:
        """Whether Results can mark this set's candidates."""
        return self.state is SetKeyState.VERIFIED

    def describe(self) -> str:
        """``"Set C: saved as a draft, not verified"``-style sentence."""
        name = f"Set {self.set_code}"
        if self.state is SetKeyState.MISSING:
            return f"{name}: no answer key."
        if self.state is SetKeyState.DRAFT:
            return f"{name}: answer key saved but not verified."
        if self.state is SetKeyState.STALE:
            reason = f" {self.issues[0]}" if self.issues else ""
            return f"{name}: answer key does not fit the active template.{reason}"
        pending = (
            f" (a newer draft, revision {self.latest.revision}, is not verified)"
            if self.has_pending_draft and self.latest is not None
            else ""
        )
        revision = self.verified.revision if self.verified is not None else 0
        return f"{name}: verified revision {revision}{pending}."


def key_overview(
    database: ProjectDatabase,
    set_codes: Sequence[str],
    plan: QuestionPlan | None,
) -> tuple[SetKeyOverview, ...]:
    """Every listed set's key position, in the order given.

    Read in one pass over the revisions. The key that *would* be used is the
    verified one when there is one, else the newest draft; it is that key
    which is checked against ``plan``, so a verified key that no longer fits
    reads as :attr:`SetKeyState.STALE` and is never reported as ready.

    Revisions are grouped by logical set, so a key stored as ``"a"`` counts
    for Set ``A``.
    """
    by_set = group_by_set((stored.set_code, stored) for stored in list_keys(database))

    overview: list[SetKeyOverview] = []
    for code in set_codes:
        revisions = by_set.get(code, [])
        if not revisions:
            overview.append(SetKeyOverview(code, SetKeyState.MISSING))
            continue
        latest = max(revisions, key=lambda item: item.revision)
        verified = max(
            (item for item in revisions if item.key.status is AnswerKeyStatus.VERIFIED),
            key=lambda item: item.revision,
            default=None,
        )
        used = verified or latest
        issues = compatibility_issues(used.key, plan) if plan is not None else ()
        if issues:
            state = SetKeyState.STALE
        elif verified is not None:
            state = SetKeyState.VERIFIED
        else:
            state = SetKeyState.DRAFT
        overview.append(SetKeyOverview(code, state, verified, latest, issues))
    return tuple(overview)


# ----------------------------------------------------------------------
# Scoring policy
# ----------------------------------------------------------------------
_POLICY_FIELDS = (
    "correct_mark",
    "blank_mark",
    "incorrect_penalty",
    "multiple_penalty",
    "mode",
    "clamp_minimum",
    "minimum_score",
)
"""Every score-affecting field. Changing any of them means a new revision."""


def _to_policy(row: ScoringPolicyRevision) -> ScoringPolicy:
    """Convert a stored revision into a detached domain policy."""
    return ScoringPolicy(
        correct_mark=Fraction(row.correct_mark),
        blank_mark=Fraction(row.blank_mark),
        incorrect_penalty=Fraction(row.incorrect_penalty),
        multiple_penalty=(
            Fraction(row.multiple_penalty) if row.multiple_penalty else None
        ),
        mode=NegativeMarking(row.mode),
        clamp_minimum=row.clamp_minimum,
        minimum_score=Fraction(row.minimum_score),
        revision=row.revision,
    )


@dataclass(frozen=True, slots=True)
class StoredPolicy:
    """One scoring-policy revision, with the row id a result references."""

    policy_id: int
    policy: ScoringPolicy
    created_at: datetime
    created_by: str = ""
    is_active: bool = True

    @property
    def revision(self) -> int:
        """Which revision this is."""
        return self.policy.revision


def _stored_policy(row: ScoringPolicyRevision) -> StoredPolicy:
    return StoredPolicy(
        policy_id=row.policy_id,
        policy=_to_policy(row),
        created_at=row.created_at,
        created_by=row.created_by,
        is_active=row.is_active,
    )


def _policy_columns(policy: ScoringPolicy) -> dict[str, Any]:
    """The stored form of a policy's score-affecting fields."""
    return {
        "correct_mark": str(policy.correct_mark),
        "blank_mark": str(policy.blank_mark),
        "incorrect_penalty": str(policy.incorrect_penalty),
        "multiple_penalty": (
            str(policy.multiple_penalty) if policy.multiple_penalty is not None else ""
        ),
        "mode": policy.mode.value,
        "clamp_minimum": policy.clamp_minimum,
        "minimum_score": str(policy.minimum_score),
    }


def active_policy(database: ProjectDatabase) -> StoredPolicy:
    """Return the policy in force, creating the default one if none exists.

    A project that has never been scored gets revision 1 with no negative
    marking - the most conservative rule, and the one least likely to be
    applied by accident.
    """
    with database.session() as session:
        row = session.scalars(
            select(ScoringPolicyRevision)
            .where(ScoringPolicyRevision.is_active.is_(True))
            .order_by(ScoringPolicyRevision.revision.desc())
            .limit(1)
        ).first()
        if row is not None:
            return _stored_policy(row)
        if database.read_only:
            # Phase 10, §42: a read-only session must never write, including
            # the conservative-default-on-first-read this function otherwise
            # performs. Return the same default values, unpersisted, so a
            # read-only open can still be inspected rather than failing here.
            return StoredPolicy(
                policy_id=0,
                policy=ScoringPolicy(),
                created_at=_now(),
                created_by="",
                is_active=True,
            )
        created = ScoringPolicyRevision(
            revision=1,
            created_at=_now(),
            is_active=True,
            **_policy_columns(ScoringPolicy()),
        )
        session.add(created)
        session.flush()
        return _stored_policy(created)


def save_policy(
    database: ProjectDatabase, policy: ScoringPolicy, *, created_by: str = ""
) -> StoredPolicy:
    """Store the policy, creating a new revision only if a rule changed.

    Returns:
        The policy now in force.

    Saving an unchanged policy is a no-op that returns the current revision.
    Creating a revision per click would make every result stale for no reason,
    and "stale" has to mean something for an operator to act on it.
    """
    proposed = _policy_columns(policy)
    with database.session() as session:
        current = session.scalars(
            select(ScoringPolicyRevision)
            .where(ScoringPolicyRevision.is_active.is_(True))
            .order_by(ScoringPolicyRevision.revision.desc())
            .limit(1)
        ).first()
        if current is not None and all(
            getattr(current, name) == proposed[name] for name in _POLICY_FIELDS
        ):
            return _stored_policy(current)

        highest = session.scalars(
            select(func.max(ScoringPolicyRevision.revision))
        ).first()
        if current is not None:
            current.is_active = False
        row = ScoringPolicyRevision(
            revision=int(highest or 0) + 1,
            created_at=_now(),
            created_by=created_by.strip(),
            is_active=True,
            **proposed,
        )
        session.add(row)
        session.flush()
        stored = _stored_policy(row)

    _LOGGER.info(
        "Scoring policy saved: revision=%d mode=%s clamp=%s",
        stored.revision,
        stored.policy.mode.value,
        stored.policy.clamp_minimum,
    )
    return stored


def get_policy(database: ProjectDatabase, policy_id: int) -> StoredPolicy | None:
    """Return one policy revision by id."""
    with database.session() as session:
        row = session.get(ScoringPolicyRevision, policy_id)
        return _stored_policy(row) if row is not None else None


def list_policies(database: ProjectDatabase) -> tuple[StoredPolicy, ...]:
    """Return every policy revision, newest first."""
    with database.session() as session:
        rows = session.scalars(
            select(ScoringPolicyRevision).order_by(
                ScoringPolicyRevision.revision.desc()
            )
        ).all()
        return tuple(_stored_policy(row) for row in rows)


# ----------------------------------------------------------------------
# Gathering a candidate's authoritative inputs
# ----------------------------------------------------------------------
@dataclass(frozen=True, slots=True)
class BatchInputs:
    """Everything a batch needs to be scored, read once.

    Read once rather than per candidate: ten thousand candidates would
    otherwise open ten thousand transactions and decode ten thousand results
    that are already in memory.
    """

    plan: QuestionPlan
    entries: tuple[ReconciliationEntry, ...]
    results: dict[int, ScanResult]
    answers: dict[int, CandidateAnswers]
    keys: Mapping[str, StoredKey]
    """Verified keys by set code, compared canonically (:class:`SetCodeMap`)."""
    policy: StoredPolicy


def gather_inputs(
    database: ProjectDatabase,
    roster_id: int,
    batch_id: str,
    template: OmrTemplate,
) -> BatchInputs:
    """Read every authoritative input for a batch, once.

    The answers come through Phase 6's
    :func:`~omr_scanner.services.review_store.effective_answers` and
    :func:`~omr_scanner.services.review_store.effective_set_codes`, never from
    the recognition result alone: those hold what the *machine* read, and
    marking against them would ignore every correction a reviewer made.
    """
    batch_id = session_population.population_key(database, batch_id)
    plan = plan_for(template)
    entries = reconciliation_store.list_entries(database, roster_id, batch_id)
    # Only the session's effective sheets supply answers (0.1.1 phase 4): a
    # rejected, superseded, re-imported, excluded or deferred sheet, or one
    # in a batch read again as a whole, never does - even if something
    # upstream still named it: no answers, no mark. Each sheet's result,
    # reviewed answers and set come from its own batch, where they were
    # recorded, whichever batch of the session that is.
    population = session_population.population(database, batch_id)
    effective = population.effective
    results = session_population.results_by_scan(database, population, effective)
    decisions = session_population.effective_answers(database, population, template, effective)
    set_codes = session_population.effective_set_codes(database, population, effective)

    answers: dict[int, CandidateAnswers] = {}
    for scan_id, result in results.items():
        decided = decisions.get(scan_id)
        found = set_codes.get(scan_id)
        answers[scan_id] = build_candidate_answers(
            result,
            plan,
            scan_id=scan_id,
            decided=decided.decided if decided else None,
            unresolved=decided.unresolved_questions if decided else (),
            set_code=found.value if found else "",
        )

    return BatchInputs(
        plan=plan,
        entries=entries,
        results=results,
        answers=answers,
        keys=verified_keys(database),
        policy=active_policy(database),
    )


def scoring_rosters(database: ProjectDatabase) -> tuple[int, ...]:
    """Every active candidate list the batch is scored against, in set order.

    One per defined set that has attendance, in the operator's set order, then
    the project's unscoped list if it has one. A project that has defined its
    sets imports one list per set and has no unscoped list at all, so asking
    only for the unscoped one - as the Results stage once did - finds nothing,
    and a multi-set examination could never be marked. A project made before
    sets existed has only the unscoped list and is scored exactly as before.

    Each list is scored separately and each candidate is marked against the
    verified key for the set read from their own script, so a set's candidates
    never meet another set's key through this.
    """
    found: list[int] = []
    for exam_set in project_sets.list_sets(database):
        roster = reconciliation_store.active_roster(database, exam_set.set_id)
        if roster is not None and roster.roster_id not in found:
            found.append(roster.roster_id)
    unscoped = reconciliation_store.active_roster(database, None)
    if unscoped is not None and unscoped.roster_id not in found:
        found.append(unscoped.roster_id)
    return tuple(found)


@dataclass(frozen=True, slots=True)
class UnreconciledRoster:
    """A candidate list that has never been reconciled against the batch.

    Scoring such a pair finds no candidates at all - not blocked ones, none -
    so it has to be stopped with a reason rather than allowed to "succeed"
    with an empty table. The case that made this matter: a batch scanned
    while the Attendance stage still held the previous one, so every set was
    reconciled against the old batch and Results marked the new one.
    """

    roster_id: int
    label: str
    """``"Set 10"``, or ``"The candidate list"`` for an unscoped roster."""
    reconciled_batch_ids: tuple[str, ...]
    """The batches it *has* been reconciled against, most recent first."""

    def describe(self, batch_id: str) -> str:
        """One sentence naming the batch it needs and the one it has."""
        text = f"{self.label} has not been reconciled against batch {batch_id[:8]}"
        if self.reconciled_batch_ids:
            text += (
                " (it was last reconciled against batch "
                f"{self.reconciled_batch_ids[0][:8]})"
            )
        return text + ". Reconcile it on the Attendance stage."


def unreconciled_rosters(
    database: ProjectDatabase, roster_ids: Sequence[int], batch_id: str
) -> tuple[UnreconciledRoster, ...]:
    """The rosters among ``roster_ids`` with no reconciliation of ``batch_id``."""
    batch_id = session_population.population_key(database, batch_id)
    labels: dict[str | None, str] = {
        exam_set.set_id: exam_set.display_label
        for exam_set in project_sets.list_sets(database)
    }
    rosters = {
        roster.roster_id: roster for roster in reconciliation_store.list_rosters(database)
    }
    found: list[UnreconciledRoster] = []
    for roster_id in roster_ids:
        batches = reconciliation_store.reconciled_batch_ids(database, roster_id)
        if batch_id in batches:
            continue
        roster = rosters.get(roster_id)
        set_id = roster.set_id if roster is not None else None
        found.append(
            UnreconciledRoster(
                roster_id=roster_id,
                label=labels.get(set_id, "The candidate list"),
                reconciled_batch_ids=batches,
            )
        )
    return tuple(found)


def inputs_for_candidate(
    data: BatchInputs, entry: ReconciliationEntry
) -> ScoringInputs:
    """Assemble one candidate's scoring inputs from a batch's."""
    scan_id, _ = working_script(entry)
    answers = data.answers.get(scan_id) if scan_id is not None else None
    key = data.keys.get(answers.set_code) if answers and answers.set_code else None
    return ScoringInputs(
        entry=entry,
        answers=answers,
        key=key.key if key else None,
        policy=data.policy.policy,
        plan=data.plan,
    )


# ----------------------------------------------------------------------
# Scoring a batch
# ----------------------------------------------------------------------
def score_batch(
    database: ProjectDatabase,
    roster_id: int,
    batch_id: str,
    template: OmrTemplate,
    *,
    computed_by: str = "",
    candidates: Sequence[str] | None = None,
    should_cancel: Callable[[], bool] | None = None,
    on_progress: Callable[[int, int], None] | None = None,
) -> ResultCounts:
    """Score a batch - or the named candidates - from authoritative inputs.

    Args:
        database: The open project database.
        roster_id: The active candidate list.
        batch_id: The batch of scripts.
        template: The template the batch was read with.
        computed_by: Who ran the scoring, if known.
        candidates: Restrict to these candidate ids. ``None`` scores all of
            them.
        should_cancel: Polled between candidates.
        on_progress: Called with ``(done, total)``.

    Returns:
        The summary counts.

    **This is a recomputation, never a patch.** Every result is produced by
    running the scorer over the stored answer string, the stored set, the
    verified key and the active policy. No existing mark is read, adjusted or
    carried forward, so a corrupted stored score cannot survive a rescore - a
    property a test asserts directly by corrupting one.

    Results are written per candidate inside one transaction at the end, so a
    cancelled run leaves the previous results intact rather than a mixture.

    Raises:
        SetCollisionError: Two of the project's sets share one canonical code
            (legacy ``A`` and ``a``). Which key marks such a script cannot be
            decided, so nothing is scored until the operator renames one.
    """
    batch_id = session_population.population_key(database, batch_id)
    set_identity.require_no_collision(
        set_identity.load(database), purpose="Calculate Results"
    )
    data = gather_inputs(database, roster_id, batch_id, template)
    wanted = set(candidates) if candidates is not None else None
    targets = [
        entry
        for entry in data.entries
        if wanted is None or entry.candidate_id in wanted
    ]

    scored: list[tuple[ReconciliationEntry, CandidateScore]] = []
    total = len(targets)
    cancelled = False
    for index, entry in enumerate(targets, start=1):
        if should_cancel is not None and should_cancel():
            cancelled = True
            _LOGGER.info(
                "Scoring cancelled after %d of %d candidate(s); nothing written",
                index - 1,
                total,
            )
            break
        scored.append((entry, score_candidate(inputs_for_candidate(data, entry))))
        if on_progress is not None:
            on_progress(index, total)

    if cancelled:
        # Nothing is written. A half-marked batch under two policies, claiming
        # to be current, is worse than a batch that was never marked - and
        # "coherent after cancellation" is not something to approximate when
        # the numbers may end up on a transcript.
        return count_results(database, roster_id, batch_id)

    moment = _now()
    with database.session() as session:
        if wanted is None:
            _drop_vanished_blocked(session, roster_id, batch_id, data.entries)
        for entry, outcome in scored:
            _write_result(
                session,
                roster_id=roster_id,
                batch_id=batch_id,
                entry=entry,
                outcome=outcome,
                data=data,
                moment=moment,
                computed_by=computed_by,
            )

    counts = count_results(database, roster_id, batch_id)
    _LOGGER.info(
        "Scored: roster=%d candidates=%d scored=%d absent=%d blocked=%d policy_rev=%d",
        roster_id,
        len(scored),
        counts.scored,
        counts.absent,
        counts.blocked,
        data.policy.revision,
    )
    return counts


def _drop_vanished_blocked(
    session: Session,
    roster_id: int,
    batch_id: str,
    entries: Sequence[ReconciliationEntry],
) -> None:
    """Remove stored *blocked* results whose entry no longer exists.

    Such a row belongs to an unregistered ID that reconciliation no longer
    produces - its only sheet was rejected / excluded, deferred, or corrected
    to a registered candidate. It never carried a mark (an unregistered entry
    cannot be scored), so removing it removes no record of one; a row with a
    mark is never touched here.
    """
    current = {entry.candidate_id for entry in entries}
    for row in session.scalars(
        select(CandidateResult)
        .where(CandidateResult.roster_id == roster_id)
        .where(CandidateResult.batch_id == batch_id)
        .where(CandidateResult.status == ResultStatus.BLOCKED.value)
    ).all():
        if row.candidate_id not in current:
            session.delete(row)
    session.flush()


def _write_result(
    session: Session,
    *,
    roster_id: int,
    batch_id: str,
    entry: ReconciliationEntry,
    outcome: CandidateScore,
    data: BatchInputs,
    moment: datetime,
    computed_by: str,
) -> None:
    """Replace one candidate's stored result with a freshly computed one."""
    row = session.scalars(
        select(CandidateResult)
        .where(CandidateResult.roster_id == roster_id)
        .where(CandidateResult.batch_id == batch_id)
        .where(CandidateResult.candidate_id == entry.candidate_id)
        .limit(1)
    ).first()
    if row is None:
        row = CandidateResult(
            roster_id=roster_id,
            batch_id=batch_id,
            candidate_id=entry.candidate_id,
            created_at=moment,
            computed_at=moment,
        )
        session.add(row)

    answers = outcome.answers
    key_id = 0
    if outcome.key is not None:
        stored = data.keys.get(outcome.key.set_code)
        key_id = stored.key_id if stored else 0

    row.scan_id = answers.scan_id if answers else None
    row.set_code = outcome.set_code
    row.answer_string = answers.answers if answers else ""
    row.machine_answer_string = answers.machine_answers if answers else ""
    row.corrected_questions = _dump_numbers(answers.corrected) if answers else ""
    row.answer_key_id = key_id or None
    row.answer_key_revision = outcome.key.revision if outcome.key else 0
    row.policy_id = data.policy.policy_id
    row.policy_revision = data.policy.revision
    row.first_question = data.plan.first_question
    row.status = outcome.status.value
    row.blocks = "|".join(
        f"{item.reason.value}:{item.detail}" for item in outcome.blocks
    )
    row.stale_reasons = ""
    row.computed_at = moment
    row.computed_by = computed_by.strip()

    breakdown = outcome.breakdown
    if breakdown is not None:
        row.question_count = breakdown.question_count
        row.correct_count = breakdown.correct_count
        row.incorrect_count = breakdown.incorrect_count
        row.blank_count = breakdown.blank_count
        row.multiple_count = breakdown.multiple_count
        row.wrong_question_count = breakdown.wrong_question_count
        row.raw_score = str(breakdown.raw_score)
        row.final_score = str(breakdown.final_score)
        row.clamped = breakdown.clamped
    else:
        row.question_count = len(answers.answers) if answers else 0
        row.correct_count = row.incorrect_count = row.blank_count = 0
        row.multiple_count = row.wrong_question_count = 0
        row.raw_score = row.final_score = ""
        row.clamped = False


# ----------------------------------------------------------------------
# Reading results back
# ----------------------------------------------------------------------
@dataclass(frozen=True, slots=True)
class StoredResult:
    """One stored result, and the provenance that explains it."""

    result_id: int
    candidate_id: str
    display_name: str
    scan_id: int | None
    set_code: str
    status: ResultStatus
    answer_string: str
    machine_answer_string: str
    corrected_questions: frozenset[int]
    answer_key_id: int | None
    answer_key_revision: int
    policy_id: int | None
    policy_revision: int
    first_question: int
    question_count: int
    correct_count: int
    incorrect_count: int
    blank_count: int
    multiple_count: int
    wrong_question_count: int
    raw_score: Fraction | None
    final_score: Fraction | None
    clamped: bool
    blocks: tuple[ScoringBlock, ...]
    stale_reasons: tuple[StaleReason, ...]
    computed_at: datetime
    computed_by: str = ""

    @property
    def is_stale(self) -> bool:
        """Whether an input has changed since this was computed."""
        return bool(self.stale_reasons)

    @property
    def has_mark(self) -> bool:
        """Whether this result carries a numeric mark."""
        return self.status is ResultStatus.SCORED and self.final_score is not None

    def describe_stale(self) -> str:
        """Why this result needs recomputing."""
        if not self.stale_reasons:
            return ""
        return "Needs recomputing because " + ", and ".join(
            reason.label for reason in self.stale_reasons
        )

    def describe_blocks(self) -> str:
        """Why this candidate could not be scored."""
        return "; ".join(item.describe() for item in self.blocks)

    def describe_provenance(self) -> str:
        """The exact revisions that produced this mark."""
        if self.answer_key_revision:
            key = f"Set {self.set_code} / revision {self.answer_key_revision}"
        else:
            key = "no answer key"
        return f"Answer key: {key} · Scoring policy: revision {self.policy_revision}"


def _parse_blocks(payload: str) -> tuple[ScoringBlock, ...]:
    """Read stored block records."""
    blocks: list[ScoringBlock] = []
    for chunk in payload.split("|"):
        if not chunk:
            continue
        reason, _, detail = chunk.partition(":")
        try:
            blocks.append(ScoringBlock(BlockReason(reason), detail))
        except ValueError:  # pragma: no cover - a reason this build cannot read
            continue
    return tuple(blocks)


def _fraction_or_none(text: str) -> Fraction | None:
    """Read a stored exact mark, or ``None`` when there is none."""
    return Fraction(text) if text else None


def _to_result(
    row: CandidateResult,
    display_name: str,
    stale: tuple[StaleReason, ...],
) -> StoredResult:
    return StoredResult(
        result_id=row.result_id,
        candidate_id=row.candidate_id,
        display_name=display_name,
        scan_id=row.scan_id,
        set_code=row.set_code,
        status=ResultStatus(row.status),
        answer_string=row.answer_string,
        machine_answer_string=row.machine_answer_string,
        corrected_questions=_load_numbers(row.corrected_questions),
        answer_key_id=row.answer_key_id,
        answer_key_revision=row.answer_key_revision,
        policy_id=row.policy_id,
        policy_revision=row.policy_revision,
        first_question=row.first_question,
        question_count=row.question_count,
        correct_count=row.correct_count,
        incorrect_count=row.incorrect_count,
        blank_count=row.blank_count,
        multiple_count=row.multiple_count,
        wrong_question_count=row.wrong_question_count,
        raw_score=_fraction_or_none(row.raw_score),
        final_score=_fraction_or_none(row.final_score),
        clamped=row.clamped,
        blocks=_parse_blocks(row.blocks),
        stale_reasons=stale,
        computed_at=row.computed_at,
        computed_by=row.computed_by,
    )


def list_results(
    database: ProjectDatabase,
    roster_id: int,
    batch_id: str,
    template: OmrTemplate | None = None,
    *,
    limit: int | None = None,
    offset: int = 0,
) -> tuple[StoredResult, ...]:
    """Return stored results with their staleness evaluated.

    ``template`` is optional: without it, staleness is judged on the key and
    policy revisions alone. With it, the candidate's *current* answers and set
    are recomputed and compared too, which is what catches a Phase 6 correction
    made since the batch was scored.
    """
    batch_id = session_population.population_key(database, batch_id)
    current = (
        gather_inputs(database, roster_id, batch_id, template)
        if template is not None
        else None
    )
    keys = verified_keys(database)
    policy = active_policy(database)
    names = {
        entry.candidate_id: entry.display_name
        for entry in reconciliation_store.list_entries(database, roster_id, batch_id)
    }
    # A stored result whose entry reconciliation no longer produces - an
    # unregistered ID whose only sheet was rejected / excluded or deferred -
    # describes nobody now, and is not shown (see _drop_vanished_blocked).
    by_id = (
        {entry.candidate_id: entry for entry in current.entries} if current else {}
    )

    with database.session() as session:
        statement = (
            select(CandidateResult)
            .where(CandidateResult.roster_id == roster_id)
            .where(CandidateResult.batch_id == batch_id)
            .order_by(CandidateResult.candidate_id)
        )
        if limit is not None:
            statement = statement.limit(limit).offset(offset)
        rows = session.scalars(statement).all()
        return tuple(
            _to_result(
                row,
                names.get(row.candidate_id, ""),
                stale_reasons_for(row, keys, policy, current, by_id.get(row.candidate_id)),
            )
            for row in rows
            if row.candidate_id in names or ResultStatus(row.status) is not ResultStatus.BLOCKED
        )


def stale_reasons_for(
    row: CandidateResult,
    keys: Mapping[str, StoredKey],
    policy: StoredPolicy,
    current: BatchInputs | None,
    entry: ReconciliationEntry | None,
) -> tuple[StaleReason, ...]:
    """Say why a stored result no longer reflects its inputs.

    Compares what the result *was computed from* against what is current. A
    stale result keeps its number - it is still a true record of what the old
    inputs produced - but must not be presented as though it were current.

    **Only a result with a mark can be made stale by a rule change.** A blocked
    result has no mark to be out of date, and flagging it would bury the reason
    it was blocked under a second warning. An absent candidate has no mark
    either: a new key or a new penalty cannot change "did not sit the paper",
    and counting them as needing recomputation would fill the queue with work
    that changes nothing. Both can still go stale through *reconciliation* -
    the one input that can turn them into somebody with a script.

    A blocked result is the exception to the exception. It carries no mark, but
    it does carry a *claim* - "no verified answer key for Set C" - and that
    claim expires the moment somebody verifies the key. Left alone it would go
    on asserting a problem that has been fixed, which is a stale statement even
    though it is not a stale number. So its stored reasons are compared against
    the reasons it would be given now, and any difference makes it stale.
    """
    status = ResultStatus(row.status)
    if status is ResultStatus.BLOCKED:
        if current is None or entry is None:
            return ()
        outcome = score_candidate(inputs_for_candidate(current, entry))
        was = {item.reason for item in _parse_blocks(row.blocks)}
        now = {item.reason for item in outcome.blocks}
        return () if was == now else (StaleReason.INPUTS,)

    reasons: list[StaleReason] = []
    if status is ResultStatus.SCORED:
        if row.policy_id != policy.policy_id:
            reasons.append(StaleReason.SCORING_POLICY)
        stored_key = keys.get(row.set_code)
        if stored_key is None or stored_key.key_id != row.answer_key_id:
            reasons.append(StaleReason.ANSWER_KEY)

    if current is not None and entry is not None:
        now_absent = entry.effective_attendance is AttendanceState.ABSENT
        was_absent = status is ResultStatus.ABSENT
        if now_absent != was_absent:
            reasons.append(StaleReason.RECONCILIATION)
        scan_id, _ = working_script(entry)
        if status is ResultStatus.SCORED and scan_id != row.scan_id:
            # The script this mark was computed from is no longer the one
            # that counts - it was rejected, or a rescan replaced it. The mark
            # is still a true record of that script, but not of this
            # candidate any more.
            reasons.append(StaleReason.RECONCILIATION)
        answers = current.answers.get(scan_id) if scan_id is not None else None
        if answers is not None and status is ResultStatus.SCORED:
            if answers.answers != row.answer_string:
                reasons.append(StaleReason.ANSWERS)
            if not same_set(answers.set_code, row.set_code):
                reasons.append(StaleReason.SET_CODE)
    return tuple(dict.fromkeys(reasons))


def get_result(
    database: ProjectDatabase,
    roster_id: int,
    batch_id: str,
    candidate_id: str,
    template: OmrTemplate | None = None,
) -> StoredResult | None:
    """Return one candidate's stored result.

    Convenience for a single lookup. It reads the whole batch to evaluate
    staleness, so calling it per candidate is quadratic: anything iterating
    over a cohort - a report, a export - wants :func:`list_results` once.
    """
    batch_id = session_population.population_key(database, batch_id)
    found = [
        item
        for item in list_results(database, roster_id, batch_id, template)
        if item.candidate_id == candidate_id
    ]
    return found[0] if found else None


def breakdown_for(
    database: ProjectDatabase, result: StoredResult
) -> ScoreBreakdown | None:
    """Regenerate one result's per-question detail from its stored inputs.

    The detail is *not* stored - a million rows for a ten-thousand-candidate
    batch, every one of which could contradict the total. Rerunning the same
    pure function over the same stored inputs gives a breakdown that agrees
    with the mark by construction.
    """
    if result.answer_key_id is None or result.policy_id is None:
        return None
    stored_key = get_key(database, result.answer_key_id)
    stored_policy = get_policy(database, result.policy_id)
    if stored_key is None or stored_policy is None:
        return None
    if len(result.answer_string) != stored_key.key.question_count:
        return None
    return score_answers(
        result.answer_string,
        stored_key.key,
        stored_policy.policy,
        first_question=result.first_question,
    )


def count_results(
    database: ProjectDatabase,
    roster_id: int,
    batch_id: str,
    template: OmrTemplate | None = None,
) -> ResultCounts:
    """Summarise a batch's results."""
    batch_id = session_population.population_key(database, batch_id)
    return summarise(list_results(database, roster_id, batch_id, template))


def summarise(results: Sequence[StoredResult]) -> ResultCounts:
    """Summarise results already read.

    Split out from :func:`count_results` because a caller that has just listed
    a batch must not list it again to count it: reading ten thousand results
    twice to show one summary line is the whole batch's work done for nothing,
    and the two reads can disagree if anything changes between them.
    """
    by_set: dict[str, int] = {}
    for item in results:
        if item.status is ResultStatus.SCORED and item.set_code:
            code = canonical_code(item.set_code)
            by_set[code] = by_set.get(code, 0) + 1
    return ResultCounts(
        registered=len(results),
        scored=sum(1 for item in results if item.status is ResultStatus.SCORED),
        absent=sum(1 for item in results if item.status is ResultStatus.ABSENT),
        blocked=sum(1 for item in results if item.status is ResultStatus.BLOCKED),
        stale=sum(1 for item in results if item.is_stale),
        by_set=by_set,
    )


def clear_results(database: ProjectDatabase, roster_id: int, batch_id: str) -> int:
    """Delete a batch's results. Returns how many were removed.

    For starting again, not for tidying up: a result is evidence of what the
    stored inputs produced, and removing it removes the only record of a mark
    somebody may already have been told.
    """
    batch_id = session_population.population_key(database, batch_id)
    with database.session() as session:
        outcome = session.execute(
            delete(CandidateResult)
            .where(CandidateResult.roster_id == roster_id)
            .where(CandidateResult.batch_id == batch_id)
        )
        removed = int(getattr(outcome, "rowcount", 0) or 0)
    _LOGGER.info("Results cleared: roster=%d removed=%d", roster_id, removed)
    return removed
