"""Write the run's reports, and print the summary a person reads.

Three outputs, from one :class:`~tools.release_validation.results.RunResult`:

``validation-results.json``
    The record. Structured for CI ingestion: every stage, every check, its
    status, duration, reason and the artifacts that explain it.
``validation-summary.md``
    The same content for a person, with failures first - because the reader of
    a failed run does not want to scroll past ninety passes to find the one
    thing that broke.
console
    A dozen lines saying which stages passed and where the report is.

Nothing here decides anything. The verdict comes from ``RunResult``, so the
console line, the Markdown heading and the process exit code cannot disagree.
"""

from __future__ import annotations

import json
from collections.abc import Iterable

from tools.release_validation import config as cfg
from tools.release_validation.results import RunResult, StageResult, Status

MARK = {
    Status.PASS: "PASS",
    Status.FAIL: "FAIL",
    Status.WARNING: "WARN",
    Status.SKIPPED: "SKIP",
}

# ANSI colours, used only when the console is a terminal that wants them.
_COLOUR = {
    Status.PASS: "\033[32m",
    Status.FAIL: "\033[31m",
    Status.WARNING: "\033[33m",
    Status.SKIPPED: "\033[90m",
}
_RESET = "\033[0m"


def _supports_colour() -> bool:
    import os
    import sys

    if os.environ.get("NO_COLOR"):
        return False
    return sys.stdout.isatty()


def write_json(run: RunResult, config: cfg.ValidationConfig) -> None:
    """Write the machine-readable report."""
    config.json_path.write_text(
        json.dumps(run.to_dict(), indent=2), encoding="utf-8"
    )


def _stage_rows(stage: StageResult, statuses: Iterable[Status]) -> list[str]:
    wanted = set(statuses)
    rows = []
    for check in stage.checks:
        if check.status not in wanted:
            continue
        detail = check.reason or check.detail
        detail = detail.replace("|", "\\|").replace("\n", " ")[:300]
        rows.append(f"| {MARK[check.status]} | {check.name.replace('|', '/')} | {detail} |")
    return rows


def write_markdown(
    run: RunResult, config: cfg.ValidationConfig, *, fail_on_warning: bool
) -> None:
    """Write the Markdown report, failures first."""
    qualified = run.qualified(fail_on_warning=fail_on_warning)
    lines: list[str] = []
    add = lines.append

    add("# OMRFlow release qualification")
    add("")
    add("<!-- Generated by tools/release_validation. Do not edit by hand. -->")
    add("")
    if not run.verified_anything:
        add("**NOTHING VERIFIED** - every requested stage was skipped.")
    else:
        add(f"**{'RELEASE QUALIFIED' if qualified else 'NOT QUALIFIED'}**")
    add("")
    add("| | |")
    add("|---|---|")
    add(f"| Run | `{run.run_id}` |")
    add(f"| Started | {run.started} |")
    add(f"| Finished | {run.finished} |")
    add(f"| Command | `{run.command_line}` |")
    for key, value in run.environment.items():
        if key == "modules":
            continue
        add(f"| {key.replace('_', ' ')} | {value} |")
    add("")

    add("## Stages")
    add("")
    add("| Stage | Result | Pass | Fail | Warn | Skip | Seconds |")
    add("|---|---|---|---|---|---|---|")
    for stage in run.stages:
        add(
            f"| {stage.name}{'' if stage.blocking else ' *(non-blocking)*'} "
            f"| **{stage.status.value}** | {stage.count(Status.PASS)} "
            f"| {stage.count(Status.FAIL)} | {stage.count(Status.WARNING)} "
            f"| {stage.count(Status.SKIPPED)} | {stage.duration_seconds:.1f} |"
        )
    add("")
    add(
        f"**Totals:** {run.count(Status.PASS)} pass, {run.count(Status.FAIL)} fail, "
        f"{run.count(Status.WARNING)} warning, {run.count(Status.SKIPPED)} skipped."
    )
    add("")

    # ------------------------------------------------- failures come first
    failures = [stage for stage in run.stages if stage.count(Status.FAIL)]
    if failures:
        add("## Failures")
        add("")
        for stage in failures:
            add(f"### {stage.name}")
            add("")
            add("| | Check | Reason |")
            add("|---|---|---|")
            lines.extend(_stage_rows(stage, [Status.FAIL]))
            add("")
            for check in stage.checks:
                if check.status is Status.FAIL and check.exception:
                    add("<details><summary>" f"{check.name} - traceback</summary>")
                    add("")
                    add("```")
                    add(check.exception[-3000:])
                    add("```")
                    add("</details>")
                    add("")

    warnings = [stage for stage in run.stages if stage.count(Status.WARNING)]
    if warnings:
        add("## Warnings")
        add("")
        for stage in warnings:
            add(f"### {stage.name}")
            add("")
            add("| | Check | Detail |")
            add("|---|---|---|")
            lines.extend(_stage_rows(stage, [Status.WARNING]))
            add("")

    skipped = [
        stage
        for stage in run.stages
        if stage.skipped_reason or stage.count(Status.SKIPPED)
    ]
    if skipped:
        add("## Not performed")
        add("")
        add("A step that was not run is not a pass.")
        add("")
        for stage in skipped:
            add(f"### {stage.name}")
            add("")
            if stage.skipped_reason:
                add(f"> {stage.skipped_reason}")
                add("")
            rows = _stage_rows(stage, [Status.SKIPPED])
            if rows:
                add("| | Check | Reason |")
                add("|---|---|---|")
                lines.extend(rows)
                add("")

    add("## Everything that passed")
    add("")
    for stage in run.stages:
        passes = stage.count(Status.PASS)
        if not passes:
            continue
        add(f"<details><summary>{stage.name} - {passes} passed</summary>")
        add("")
        add("| | Check | Detail |")
        add("|---|---|---|")
        lines.extend(_stage_rows(stage, [Status.PASS]))
        add("")
        add("</details>")
        add("")

    config.summary_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def print_summary(run: RunResult, config: cfg.ValidationConfig, *, fail_on_warning: bool) -> None:
    """The console summary, in the shape §15 of the brief asks for."""
    colour = _supports_colour()
    width = 60

    def paint(status: Status, text: str) -> str:
        if not colour:
            return text
        return f"{_COLOUR[status]}{text}{_RESET}"

    print()
    print("=" * width)
    print("OMRFLOW RELEASE QUALIFICATION")
    print("=" * width)
    print()

    label_width = max((len(stage.name) for stage in run.stages), default=20) + 2
    for stage in run.stages:
        suffix = "" if stage.blocking else "  (non-blocking)"
        print(
            f"{stage.name:<{label_width}}{paint(stage.status, stage.status.value)}{suffix}"
        )

    print()
    totals = (
        f"TOTAL: {run.count(Status.PASS)} PASS / {run.count(Status.FAIL)} FAIL "
        f"/ {run.count(Status.WARNING)} WARNING / {run.count(Status.SKIPPED)} SKIPPED"
    )
    print(totals)

    qualified = run.qualified(fail_on_warning=fail_on_warning)
    if not run.verified_anything:
        verdict = "NOTHING VERIFIED"
    elif qualified:
        verdict = "RELEASE QUALIFIED"
    else:
        verdict = "NOT QUALIFIED"
    print(f"RESULT: {paint(Status.PASS if qualified else Status.FAIL, verdict)}")

    if not qualified:
        print()
        if not run.verified_anything:
            print("Every requested stage was skipped, so nothing was checked:")
            for stage in run.substantive_stages:
                if stage.skipped_reason:
                    print(f"  - [{stage.name}] {stage.skipped_reason}")
        elif run.blocking_failures:
            print("Release-blocking failures:")
            for stage in run.blocking_failures:
                for check in stage.checks:
                    if check.status is Status.FAIL:
                        print(f"  - [{stage.name}] {check.name}")
                        if check.reason:
                            print(f"      {check.reason[:200]}")
        elif fail_on_warning:
            print("No failures, but --fail-on-warning was given and warnings exist.")

    print()
    print("Report:")
    try:
        summary = config.summary_path.relative_to(cfg.REPOSITORY_ROOT)
        results = config.json_path.relative_to(cfg.REPOSITORY_ROOT)
    except ValueError:  # pragma: no cover - results outside the repository
        summary, results = config.summary_path, config.json_path
    print(f"  {summary}")
    print(f"  {results}")
    print("=" * width)
