"""One-off generator for the GitHub Social Preview image.

Purpose:
    Compose ``docs/images/github-social-preview.svg`` (the editable source)
    from the repository's authoritative ``logo.svg`` plus one tagline line,
    and rasterise it to ``docs/images/github-social-preview.png`` - the
    1280 x 640 image GitHub shows on repository cards, topic pages and link
    previews.

    The logo's path data is copied verbatim out of ``logo.svg`` and placed
    with a single uniform scale and translation, so its geometry, colours and
    aspect ratio are exactly the logo's own. Nothing about the logo is drawn
    here.

Not part of the installed package or the runtime import graph - run by hand
whenever ``logo.svg`` or the tagline changes, and commit both outputs, the
same way ``generate_branding_assets.py`` handles the application icon. Uses
only PySide6, which is already a dependency. Run it on Windows with Qt's
normal platform plugin: the ``offscreen`` plugin has no fonts and renders the
tagline as empty boxes.

GitHub does not pick this file up by itself: the Social Preview is a
repository setting, uploaded through Settings -> General -> Social preview.

Usage:
    python scripts/generate_social_preview.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from PySide6.QtCore import QByteArray
from PySide6.QtGui import QColor, QImage, QPainter
from PySide6.QtSvg import QSvgRenderer
from PySide6.QtWidgets import QApplication

ROOT = Path(__file__).resolve().parents[1]
LOGO_SVG = ROOT / "logo.svg"
OUT_DIR = ROOT / "docs/images"
OUT_SVG = OUT_DIR / "github-social-preview.svg"
OUT_PNG = OUT_DIR / "github-social-preview.png"

WIDTH, HEIGHT = 1280, 640

# Colours are the existing ones, not new choices: the background is the
# theme's SURFACE_SUNKEN and the tagline its TEXT_SECONDARY
# (``src/omr_scanner/gui/theme/tokens.py``); the logo keeps its own
# #1C2024 / #AC1F24 fills.
BACKGROUND = "#FAFAFA"
TAGLINE_COLOUR = "#5C5C60"
TAGLINE = "Open-source OMR &amp; Exam Grading"
TAGLINE_SIZE = 46
# Windows' system UI font, so no font is added for this image. A single
# family on purpose: QtSvg does not resolve a comma-separated fallback list
# and silently renders the whole list in its default font (Tahoma) instead.
FONT_FAMILY = "Segoe UI"

# Bounding box of the drawn paths inside logo.svg's 1254 x 1254 viewBox
# (min/max of every path's coordinates). The canvas has generous empty
# margins around the wordmark, so placing by viewBox would waste space.
LOGO_BOX = (150, 324, 1098, 937)
LOGO_HEIGHT = 360
GAP = 52


def logo_group() -> str:
    """Return the ``<g>...</g>`` element of ``logo.svg``, unchanged."""
    match = re.search(r"<g\b.*</g>", LOGO_SVG.read_text(encoding="utf-8"), re.DOTALL)
    if match is None:
        raise RuntimeError(f"No <g> element in {LOGO_SVG}")
    return match.group(0)


def compose_svg() -> str:
    """Build the social-preview SVG: background, centred logo, tagline."""
    x0, y0, x1, y1 = LOGO_BOX
    scale = LOGO_HEIGHT / (y1 - y0)
    logo_width = (x1 - x0) * scale
    block_height = LOGO_HEIGHT + GAP + TAGLINE_SIZE
    top = (HEIGHT - block_height) / 2
    left = (WIDTH - logo_width) / 2
    baseline = top + LOGO_HEIGHT + GAP + TAGLINE_SIZE * 0.78
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate_social_preview.py from logo.svg.
     Edit the script, not this file. -->
<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}"
     viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-labelledby="title">
  <title id="title">OMRFlow - {TAGLINE}</title>
  <rect width="{WIDTH}" height="{HEIGHT}" fill="{BACKGROUND}"/>
  <g transform="translate({left:.2f} {top:.2f}) scale({scale:.6f}) translate({-x0} {-y0})">
    {logo_group()}
  </g>
  <text x="{WIDTH / 2:.0f}" y="{baseline:.2f}" text-anchor="middle"
        font-family="{FONT_FAMILY}" font-size="{TAGLINE_SIZE}"
        fill="{TAGLINE_COLOUR}">{TAGLINE}</text>
</svg>
"""


def main() -> int:
    """Write the SVG source and its 1280 x 640 PNG rendering."""
    QApplication.instance() or QApplication([])

    svg = compose_svg()
    renderer = QSvgRenderer(QByteArray(svg.encode("utf-8")))
    if not renderer.isValid():
        print("Composed SVG did not load", file=sys.stderr)
        return 1

    image = QImage(WIDTH, HEIGHT, QImage.Format.Format_RGB32)
    image.fill(QColor(BACKGROUND))
    painter = QPainter(image)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing)
    painter.setRenderHint(QPainter.RenderHint.TextAntialiasing)
    renderer.render(painter, image.rect())
    painter.end()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_SVG.write_text(svg, encoding="utf-8", newline="\n")
    if not image.save(str(OUT_PNG)):
        print(f"Failed to write {OUT_PNG}", file=sys.stderr)
        return 1
    print(f"Wrote {OUT_SVG}")
    print(f"Wrote {OUT_PNG} ({WIDTH}x{HEIGHT})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
