"""Generate the Windows VERSIONINFO resource stamped into ``OMRFlow.exe``.

Purpose:
    Let Windows' own file-properties dialog answer "which build is this?" -
    the first thing a support request needs and the last thing a tester
    thinks to look up. Derived from :mod:`omr_scanner._version`, so the
    executable's metadata cannot disagree with the application's own About
    dialog.

Usage:
    python packaging/make_version_info.py packaging/build/file_version_info.txt

Why the numeric version needs a mapping:
    Windows insists on exactly four integers and has no notion of a
    prerelease. :func:`omr_scanner._version.numeric_version` does that
    mapping - it is shared with the installer, which needs the same four
    integers for its own ``VersionInfoVersion``. The human-readable string
    in ``StringFileInfo`` keeps the real version, and *that* is what the
    properties dialog shows a user.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from omr_scanner import (
    APPLICATION_NAME,
    COPYRIGHT_YEAR,
    RELEASE_CHANNEL,
    __version__,
)
from omr_scanner._version import numeric_version
from omr_scanner.gui.about_dialog import DEVELOPER_NAME, TAGLINE

TEMPLATE = """\
# Generated by packaging/make_version_info.py - do not edit by hand.
# Regenerated on every build from omr_scanner._version.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={numeric},
    prodvers={numeric},
    mask=0x3f,
    flags={flags},
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', {company!r}),
         StringStruct('FileDescription', {description!r}),
         StringStruct('FileVersion', {version!r}),
         StringStruct('InternalName', {name!r}),
         StringStruct('LegalCopyright', {copyright!r}),
         StringStruct('OriginalFilename', {filename!r}),
         StringStruct('ProductName', {name!r}),
         StringStruct('ProductVersion', {version!r}),
         StringStruct('Comments', {comments!r})])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""

VS_FF_PRERELEASE = 0x00000002
"""Windows' own "this is a prerelease build" flag.

Set for anything that is not a stable release, so the operating system's
file-properties dialog agrees with the About dialog about the build's
maturity rather than quietly presenting an Alpha as finished.
"""


def render() -> str:
    """Return the resource file's contents."""
    return TEMPLATE.format(
        numeric=numeric_version(),
        flags=hex(VS_FF_PRERELEASE) if RELEASE_CHANNEL.is_prerelease else "0x0",
        company=DEVELOPER_NAME,
        description=f"{APPLICATION_NAME} - {TAGLINE}",
        version=__version__,
        name=APPLICATION_NAME,
        copyright=f"(c) {COPYRIGHT_YEAR} {DEVELOPER_NAME}. MIT Licence.",
        filename=f"{APPLICATION_NAME}.exe",
        comments=f"{RELEASE_CHANNEL.value} release.",
    )


def main(argv: list[str] | None = None) -> int:
    """Write the resource file named on the command line."""
    arguments = sys.argv[1:] if argv is None else argv
    if len(arguments) != 1:
        print(__doc__.strip().splitlines()[-1], file=sys.stderr)
        print("usage: make_version_info.py <output-path>", file=sys.stderr)
        return 2

    destination = Path(arguments[0])
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(render(), encoding="utf-8")
    print(f"{destination}: {APPLICATION_NAME} {__version__} {numeric_version()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
