# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller specification for the OMRFlow Windows application bundle.

Produces a one-directory build (`dist/OMRFlow/`) rather than a single file.
One-file unpacks the whole of Qt and OpenCV to a temporary directory on every
launch, which costs seconds of start-up and confuses antivirus software; a
directory is also what an installer wants to lay down.

Run through `scripts/release/Build-App.ps1`, which sets the version
environment variables this file reads. Building it directly still works, but
the executable's Windows metadata will then say "unknown".

What this file is responsible for:
  * finding the application's own bundled resources (icons, branding), which
    are loaded through `importlib.resources` at runtime and so are invisible
    to PyInstaller's import analysis;
  * excluding the development-only dependency tree, which otherwise adds
    over a hundred megabytes of test and build tooling to a user download;
  * stamping the executable with the version.
"""

from __future__ import annotations

import importlib.util
import os
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files

SPEC_DIR = Path(SPECPATH).resolve()
PROJECT_ROOT = SPEC_DIR.parent
PACKAGE_ROOT = PROJECT_ROOT / "src" / "omr_scanner"
BUILD_DIR = SPEC_DIR / "build"

APP_NAME = "OMRFlow"
ICON = PACKAGE_ROOT / "gui" / "resources" / "branding" / "icon.ico"
VERSION_RESOURCE = BUILD_DIR / "file_version_info.txt"


def _load_version_module():
    """Import `omr_scanner._version` from its file, without the package.

    Importing `omr_scanner` itself would pull in the application; `_version`
    promises in its own docstring to be free of third-party and intra-project
    imports, which is exactly what makes it safe to load alone here.
    """
    spec = importlib.util.spec_from_file_location(
        "_omrflow_version", PACKAGE_ROOT / "_version.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_version = _load_version_module()

# ---------------------------------------------------------- the build commit
# `_version.build_identifier()` finds the source commit either from a Git
# checkout or from an environment variable. A frozen build has neither: there
# is no `.git` beside the executable, and the variable Build-App.ps1 exports
# belongs to the *build* process and is gone by the time a user runs the
# application. The result was a packaged build that reported a bare version,
# so the build identifier in the About dialog and in every diagnostic bundle
# could not be traced back to a revision - which is the one thing it exists
# to do.
#
# Writing it into a runtime hook fixes that: PyInstaller executes these before
# any application module is imported, so the variable is set before
# `_version` is first asked. `setdefault` rather than assignment, so a commit
# supplied in the real environment still wins, which is what a developer
# bisecting a packaged build needs.
BUILD_DIR.mkdir(parents=True, exist_ok=True)
_build_commit = os.environ.get(_version.BUILD_COMMIT_ENVIRONMENT_VARIABLE, "").strip()
_commit_hook = BUILD_DIR / "pyi_rth_omrflow_build_commit.py"
_commit_hook.write_text(
    "# Generated by packaging/omrflow.spec at build time. Do not edit.\n"
    + (
        "import os\n"
        f"os.environ.setdefault("
        f"{_version.BUILD_COMMIT_ENVIRONMENT_VARIABLE!r}, {_build_commit!r})\n"
        if _build_commit
        else "# No source commit was available when this build was made.\n"
    ),
    encoding="utf-8",
)

# The GUI resolves icons and branding through `importlib.resources` against
# the installed package, so nothing imports these paths and PyInstaller's
# analysis cannot see them. Collected explicitly, preserving the package
# layout `omr_scanner.gui.icons` expects to find them in.
datas = collect_data_files(
    "omr_scanner",
    includes=[
        "gui/resources/icons/lucide/*.svg",
        "gui/resources/icons/lucide/LICENSE",
        "gui/resources/branding/*",
        "resources/**/*",
    ],
)

# Everything a developer needs and a user does not. Left in, these add well
# over a hundred megabytes to the download and pull test frameworks into a
# shipped application.
excludes = [
    "pytest",
    "pytest_qt",
    "pytest_cov",
    "_pytest",
    "mypy",
    "ruff",
    "PyInstaller",
    "setuptools",
    "pip",
    "wheel",
    "build",
    "tkinter",
    "matplotlib",
    "IPython",
    "jupyter",
    "notebook",
    "sphinx",
    "pydoc_data",
    # Qt modules OMRFlow does not use. PySide6 is by far the largest single
    # contributor to the bundle, and these are its heaviest unused parts.
    "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineWidgets",
    "PySide6.QtWebEngineQuick",
    "PySide6.QtQuick",
    "PySide6.QtQuick3D",
    "PySide6.QtQml",
    "PySide6.Qt3DCore",
    "PySide6.Qt3DRender",
    "PySide6.QtMultimedia",
    "PySide6.QtMultimediaWidgets",
    "PySide6.QtCharts",
    "PySide6.QtDataVisualization",
    "PySide6.QtBluetooth",
    "PySide6.QtNfc",
    "PySide6.QtPositioning",
    "PySide6.QtLocation",
    "PySide6.QtSerialPort",
    "PySide6.QtSensors",
    "PySide6.QtTest",
    "PySide6.QtDesigner",
    "PySide6.QtHelp",
    "PySide6.QtSql",
    "PySide6.QtOpenGLFunctions",
    "PySide6.QtRemoteObjects",
    "PySide6.QtScxml",
    "PySide6.QtSpatialAudio",
    "PySide6.QtStateMachine",
    "PySide6.QtTextToSpeech",
    "PySide6.QtWebChannel",
    "PySide6.QtWebSockets",
]

analysis = Analysis(
    [str(PACKAGE_ROOT / "main.py")],
    pathex=[str(PROJECT_ROOT / "src")],
    binaries=[],
    datas=datas,
    # `omr_scanner.tools.*` are reached by `python -m`, never imported by the
    # GUI, so the analysis would drop them - and with them the qualification
    # harness a tester may be asked to run.
    hiddenimports=[
        "omr_scanner.tools.benchmark_stress",
        "omr_scanner.tools.phase10_qualification",
    ],
    hookspath=[],
    hooksconfig={},
    # Sets OMRFLOW_BUILD_COMMIT before any application module is imported -
    # see "the build commit" above.
    runtime_hooks=[str(_commit_hook)],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)

pyz = PYZ(analysis.pure)

executable = EXE(
    pyz,
    analysis.scripts,
    [],
    exclude_binaries=True,
    name=APP_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    # A desktop application: no console window behind the GUI. Diagnostics go
    # to the per-user log file, which `SUPPORT.md` explains how to find.
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ICON) if ICON.is_file() else None,
    version=str(VERSION_RESOURCE) if VERSION_RESOURCE.is_file() else None,
)

collection = COLLECT(
    executable,
    analysis.binaries,
    analysis.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name=APP_NAME,
)
